### ISSUE TITLE
When toggling Dark Mode in iOS/ iPadOS, the app should immediately change their appearances even though suspended in the background.

### ISSUE THREAD

**Issue by gaodeng** [OneKeyHQ/app-monorepo#1678]
**Describe the bug**
When toggling Dark Mode in iOS/ iPadOS, the app should immediately change their appearances even though suspended in the background.

https://user-images.githubusercontent.com/1118249/193972094-2dd14e95-c9f8-40ff-8f24-99cb1e357f26.mov

**Additional context**
Possible solution: Use DynamicColorIOS on iOS / iPadOS platforms

**Comment by revan-zhang** [comment]
Hi @gaodeng 
Thanks for reporting this issue. This seems to be an UI experience related issue. 

We will be evaluating the priority of this internally to determine if this area needs to be fixed ASAP. Of course, if you have good suggestions here or how to fix it, PR is welcome.

**Comment by rayston92** [comment]
Good issue @gaodeng 

Will definitely check it out and comeback to you asap.

**Comment by rayston92** [comment]
We are sunsetting v4 App, check it out w/ v5 version.
