### ISSUE TITLE
[BUG]: Xcode packaging error

### ISSUE THREAD

**Issue by mnz12138** [OneKeyHQ/app-monorepo#1884]
**Xcode14.0.1 Packaging error**
The certificate is configured

**The error is as follows: What else do you need to configure when packing?**
error build: Command PhaseScriptExecution failed with a nonzero exit code

**Comment by sunnylqm** [comment]
can you elaborate on your action steps? And screenshot the error in Xcode

**Comment by mnz12138** [comment]
> can you elaborate on your action steps? And screenshot the error in Xcode

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:720:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/xxx/Desktop/app-monorepo/node_modules/metro/src/shared/output/bundle.js:14:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by revan-zhang** [comment]
Which node.js version? The unrecognized syntax seems like due to an outdated version of node.js.Try to update node.js version to LTS and try again?

**Comment by mnz12138** [comment]
> Which node.js version? The unrecognized syntax seems like due to an outdated version of node.js.Try to update node.js version to LTS and try again?

v16.18.0

**Comment by mnz12138** [comment]
<img width="717" alt="截屏2022-11-23 15 05 09" src="https://user-images.githubusercontent.com/13588391/203489133-55a63a55-8087-4a1b-8f61-bc006bb45aba.png">

**Comment by sunnylqm** [comment]
it still appears to be a deprecated node version. run `npx react-native info` to see your environment info

**Comment by mnz12138** [comment]
<img width="693" alt="截屏2022-11-23 16 11 50" src="https://user-images.githubusercontent.com/13588391/203498290-23acef40-c203-4f4f-8dcf-87622eff0744.png">

**Comment by revan-zhang** [comment]
This may be caused by xcode using the wrong node.js version, especially when using multi-version management tools such as nvm.

You can refer to this stackoverflow answer for example to try https://stackoverflow.com/questions/34035421/xcode-using-wrong-node-js-version

**Comment by mnz12138** [comment]
What version of node.js do you package with?

**Comment by sunnylqm** [comment]
Currently only node v16 tested

**Comment by mnz12138** [comment]
Can you send out your packing steps

**Comment by sunnylqm** [comment]
1. git clone
2. yarn
3. yarn ios (`yarn m1:ios` if you are using m1 mac)

**Comment by mnz12138** [comment]
This seems to be running into the emulator, which I expect is the output ipa.

**Comment by sunnylqm** [comment]
we use https://docs.expo.dev/build/introduction/ to build testing/production app

**Comment by mnz12138** [comment]
> we use https://docs.expo.dev/build/introduction/ to build testing/production app

成功解决！另一个问题，在.env文件中配置环境变量，获取为空为啥？

**Comment by mnz12138** [comment]
> we use https://docs.expo.dev/build/introduction/ to build testing/production app

A successful solution! Another question, configuring environment variables in the .env file, why is it null?

**Comment by mnz12138** [comment]
> we use https://docs.expo.dev/build/introduction/ to build testing/production app

A successful solution! Another question, configuring environment variables in.env file, can't get the value why?

**Comment by mnz12138** [comment]
The web side can be obtained, why can't the app be obtained?

**Comment by mnz12138** [comment]
> > we use https://docs.expo.dev/build/introduction/ to build testing/production app
> 
> A successful solution! Another question, configuring environment variables in.env file, can't get the value why?

The web side can be obtained, why can't the app be obtained?

**Comment by revan-zhang** [comment]
Hi @mnz12138 . APP need config env at expo dashboard.

**Comment by mnz12138** [comment]
> Hi @mnz12138 . APP need config env at expo dashboard.

Hello, is it the Secrets setting in expo dashboard?

**Comment by revan-zhang** [comment]
At present, there are no new additional environment variables in expo. It just means that for APP-related packaging, if you want to inject environment variables correctly, you need to set them again at expo side. You can refer to some configurations of our CI.

**Comment by mnz12138** [comment]
> At present, there are no new additional environment variables in expo. It just means that for APP-related packaging, if you want to inject environment variables correctly, you need to set them again at expo side. You can refer to some configurations of our CI.

I set the values of the environment variables in the .env file, but did not enter the values when the simulator was running console.log.
