### ISSUE TITLE
[Feature] Migration of the OneKey Chrome Extension to the V3 Manifest

### ISSUE THREAD

**Issue by ccp-tezza** [OneKeyHQ/app-monorepo#1992]
I was wondering about the timeline, priority, and plan for migration of the OneKey extension to the new [Chrome V3 Manifest](https://developer.chrome.com/docs/extensions/mv3/mv3-migration/)

**Comment by revan-zhang** [comment]
Thanks for the reminder, this is in our plan, we will switch to v3 version as soon as possible in early 2023.

**Comment by sidmorizon** [comment]
V3 Manifest migration done
