### ISSUE TITLE
Is there a GitHub repo for your endpoint backend?

### ISSUE THREAD

**Issue by markaltmaier** [OneKeyHQ/app-monorepo#2030]
I'm trying to replace this variable

`const DEFAULT_ONLINE_ENDPOINT = 'https://fiat.onekeycn.com';
`
with my own server but, I can't find any repo for it.

**Comment by sunnylqm** [comment]
sorry the server repo is currently private

**Comment by revan-zhang** [comment]
Currently, our server is not open source. Although we use our own centralized server, it is only for improving the experience of fetching token balance.
But we will also have a plan to open source the server in the future, thank you for your attention.
