### ISSUE TITLE
[BUG]: 我该如何配置秘钥？？Execution failed for task ':lib-keys-secret:buildCMakeRelWithDebInfo'. [stderr] > Build command failed. [stderr] Error while executing process /home/expo/Android/Sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /home/expo/workingdir/build/packages/app/android/lib-keys-secret/.cxx/RelWithDebInfo/483b1t4v/armeabi-v7a keys}

### ISSUE THREAD

**Issue by Toketec** [OneKeyHQ/app-monorepo#2047]
**Prerequisites**
EXPO打包安卓时候，提示和秘钥相关的问题，无法执行
但是根据文档说，社区开发者需要前往android/script执行对应脚本获取秘钥进行配置。然而不管用：

![image](https://user-images.githubusercontent.com/44367138/203131367-0b6464f4-d40b-4883-80e6-b9e74ffc0592.png)

![image](https://user-images.githubusercontent.com/44367138/203131529-31b3a542-2cb7-45c0-a8c7-bf3ee0c0cace.png)

这是Expo的报错信息：
[stderr] FAILURE: Build failed with an exception.
[stderr] * What went wrong:
[stderr] Execution failed for task ':lib-keys-secret:buildCMakeRelWithDebInfo'.
[stderr] > Build command failed.
[stderr] Error while executing process /home/expo/Android/Sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /home/expo/workingdir/build/packages/app/android/lib-keys-secret/.cxx/RelWithDebInfo/483b1t4v/armeabi-v7a keys}
[stderr]   ninja: Entering directory `/home/expo/workingdir/build/packages/app/android/lib-keys-secret/.cxx/RelWithDebInfo/483b1t4v/armeabi-v7a'
[stderr]   [1/3] Building C object CMakeFiles/keys.dir/keys.c.o
[stderr]   FAILED: CMakeFiles/keys.dir/keys.c.o 
[stderr]   /home/expo/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7-none-linux-androideabi23 --gcc-toolchain=/home/expo/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/expo/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/sysroot -Dkeys_EXPORTS  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security  -O2 -g -DNDEBUG -fPIC -fvisibility=hidden -MD -MT CMakeFiles/keys.dir/keys.c.o -MF CMakeFiles/keys.dir/keys.c.o.d -o CMakeFiles/keys.dir/keys.c.o   -c /home/expo/workingdir/build/packages/app/android/lib-keys-secret/src/main/cpp/keys.c
[stderr]   /home/expo/workingdir/build/packages/app/android/lib-keys-secret/src/main/cpp/keys.c:18:57: error: use of undeclared identifier 'authorizedAppSha1'
[stderr]       if (checkSecurityPermission(env, context, (char **) authorizedAppSha1, 3)) {
[stderr]                                                           ^
[stderr]   /home/expo/workingdir/build/packages/app/android/lib-keys-secret/src/main/cpp/keys.c:19:16: warning: implicit declaration of function 'getDecryptedKey' is invalid in C99 [-Wimplicit-function-declaration]
[stderr]           return getDecryptedKey(env, liteInitGPCParams, sizeof(liteInitGPCParams));
[stderr]                  ^
[stderr]   /home/expo/workingdir/build/packages/app/android/lib-keys-secret/src/main/cpp/keys.c:19:63: error: use of undeclared identifier 'liteInitGPCParams'
[stderr]           return getDecryptedKey(env, liteInitGPCParams, sizeof(liteInitGPCParams));
[stderr]                                                                 ^
[stderr]   /home/expo/workingdir/build/packages/app/android/lib-keys-secret/src/main/cpp/keys.c:19:37: error: use of undeclared identifier 'liteInitGPCParams'
[stderr]           return getDecryptedKey(env, liteInitGPCParams, sizeof(liteInitGPCParams));
[stderr]                                       ^
[stderr]   1 warning and 3 errors generated.
[stderr]   [2/3] Building C object CMakeFiles/keys.dir/validation.c.o
[stderr]   ninja: build stopped: subcommand failed.

**Comment by ByteZhang1024** [comment]
不用管密钥的问题。
检查 /home/expo/workingdir/build/packages/app/android/keys.secret 文件是否存在，如果有删掉即可。

**Comment by ByteZhang1024** [comment]
如果文件不存在还有问题可能是 EXPO 环境的问题。
将 packages/app/android/lib-keys-secret/src/main/cpp/keys.c 文件中 如下内容删掉即可
```
#if (HAS_KEYS == 1)
    if (checkSecurityPermission(env, context, (char **) authorizedAppSha1, 3)) {
        return getDecryptedKey(env, liteInitGPCParams, sizeof(liteInitGPCParams));
    }
    LOGD("create process failure");
    exit(0);
    return (*env)->NewStringUTF(env,"");
#else
```

**Comment by Toketec** [comment]
Thank you~~，the problem has been resolved
