### ISSUE TITLE
i want to create address specific privatekey and pubkey and wif importable to core wallet 

### ISSUE THREAD

**Issue by ForsaHQ** [OneKeyHQ/app-monorepo#2064]
i don't know how it's possible to create a address specific privkatekey and pubkey 
the privatekey created to sign message i can't seem to be able to convert it to wif to import it in core wallet directly 

am i missing something

**Comment by revan-zhang** [comment]
Hi @pec-build 
Currently our wallet cannot generate "address specific privkatekey and pubkey".Thanks for your feedback.
