### ISSUE TITLE
[BUG]:IOS端扫描二维码时，没有反应无法识别，选择一张图片可以识别。但是安卓端功能正常

### ISSUE THREAD

**Issue by Toketec** [OneKeyHQ/app-monorepo#2067]
我运行的是3.16.0最后一个版本代码
系统版本：ios15.1 、   ios14.6

**Comment by sunnylqm** [comment]
请尝试最新版本

**Comment by Toketec** [comment]
谢谢，新版本验证ios可以扫描二维码了~~~可以提示一下咱们在哪一次提交中修复了这个问题嘛？因为现在我正基于16版本进行diy开发，合并后冲突比较多，所以想直接只修复这个问题，万分感谢~~~

**Comment by sunnylqm** [comment]
我们迭代很快，说实话我也很难回想起来……

**Comment by Toketec** [comment]
Thanks♪(･ω･)ﾉ，resolved~
