### ISSUE TITLE
[Feature] Add Lightning Network to Bitcoin

### ISSUE THREAD

**Issue by EryX0** [OneKeyHQ/app-monorepo#2128]
not sure if this has been requested ( couldn't find ) or even if it can be requested here...
but, the title.
lightning network allow extremely low-fee transactions for Bitcoin and its very useful for small amount purchases and many website/stores already support Lightning.

**Comment by rayston92** [comment]
lightning network is on our roadmap.

**Comment by stackia** [comment]
We are currently working on lighting network recently. Stay tuned, we'll release soon!

https://github.com/OneKeyHQ/app-monorepo/pull/3387

**Comment by ByteZhang1024** [comment]
Done.
