### ISSUE TITLE
[Feature] Request for submitting it to Flathub

### ISSUE THREAD

**Issue by proletarius101** [OneKeyHQ/app-monorepo#2156]
**Is your feature request related to a problem? Please describe.**
[Flathub](https://flathub.org/home) is a centralized repo like Google Play for desktop apps on Linux. Publishing it will expose OneKey Wallet to a wider community of Linux users.

**Describe the solution you'd like**
It would be nice if you agree that I submit it to Flathub: https://github.com/flathub/flathub/pull/3692. It's simply files extracted from your AppImage + metadata files. All are [open source](https://github.com/flathub/flathub/pull/3692/files) and auditable. The packaging happens in Flathub.org's server.

**Comment by revan-zhang** [comment]
Hi @proletarius101
Thanks for your support with the OneKey Wallet project. For third-party platforms such as Flathub, as long as "unofficial release" is marked, we currently have no objection.
