### ISSUE TITLE
[BUG]:

### ISSUE THREAD

**Issue by cforcross** [OneKeyHQ/app-monorepo#2160]
when i run `yarn` or `yarn install` i get ther error on the screnshot below. don't know why exactly. followed the installation steps on the docs. thanks
![win](https://user-images.githubusercontent.com/61464091/206163533-fa0204f0-9224-4679-b74c-8116f39fe00b.PNG)

**Comment by revan-zhang** [comment]
Hi @cforcross 
It seems to be a network-related reason, you can use `yarn --verbose` to get more information to confirm your problem.
