### ISSUE TITLE
[BUG]:when press yarn to install dependencies

### ISSUE THREAD

**Issue by squaredlogics** [OneKeyHQ/app-monorepo#2185]
**Prerequisites**
Press "yarn" to install dependencies

**Describe the bug**
➤ YN0007: │ core-js-pure@npm:3.26.1 must be built because it never has been before or the last one failed
➤ YN0007: │ realm@npm:11.0.0-rc.0 [861fd] must be built because it never has been before or the last one failed
➤ YN0007: │ electron@npm:21.1.1 must be built because it never has been before or the last one failed
➤ YN0007: │ electron@npm:19.1.3 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.15.11 must be built because it never has been before or the last one failed
➤ YN0007: │ keytar@npm:7.9.0 must be built because it never has been before or the last one failed
➤ YN0007: │ secp256k1@npm:4.0.3 must be built because it never has been before or the last one failed
➤ YN0007: │ web3-bzz@npm:1.7.3 must be built because it never has been before or the last one failed
➤ YN0007: │ web3-shh@npm:1.7.3 must be built because it never has been before or the last one failed
➤ YN0007: │ protobufjs@npm:6.11.3 must be built because it never has been before or the last one failed
➤ YN0007: │ keccak@npm:3.0.2 must be built because it never has been before or the last one failed
➤ YN0007: │ bigint-buffer@npm:1.1.5 must be built because it never has been before or the last one failed
➤ YN0007: │ tiny-secp256k1@npm:1.1.6 must be built because it never has been before or the last one failed
➤ YN0007: │ secp256k1@npm:3.8.0 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.6.5 must be built because it never has been before or the last one failed
➤ YN0007: │ better-sqlite3@npm:7.6.2 must be built because it never has been before or the last one failed
➤ YN0007: │ bufferutil@npm:4.0.6 must be built because it never has been before or the last one failed
➤ YN0007: │ utf-8-validate@npm:5.0.8 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:2.6.12 must be built because it never has been before or the last one failed
➤ YN0009: │ @onekeyhq/app-monorepo@workspace:. couldn't be built successfully (exit code 2, logs can be found here: C:\Users\HP\AppData\Local\Temp\xfs-816180f3\build.log)
➤ YN0007: │ @onekeyhq/app@workspace:packages/app must be built because it never has been before or the last one failed
➤ YN0007: │ @onekeyhq/desktop@workspace:packages/desktop must be built because it never has been before or the last one failed
➤ YN0007: │ web3@npm:1.7.3 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 3m 26s
➤ YN0000: Failed with errors in 3m 35s

**Comment by revan-zhang** [comment]
Seems like a windows platform related issue, could you please upload C:\Users\HP\AppData\Local\Temp\xfs-816180f3\build.log for more detail? or using `yarn --verbose` for much more output.

**Comment by squaredlogics** [comment]
[build.log](https://github.com/OneKeyHQ/app-monorepo/files/10207800/build.log)
this is log file.
My node version
v16.15.0
Yarn version
3.3.0
Expo Version
5.4.9

**Comment by revan-zhang** [comment]
Thank you for your information.
Currently, our developers local environment is all macos or linux, also in CI tasks. Some script instructions do not consider with the Windows platform. We will consider fixing these windows platform releated script issue this week.

**Comment by sunnylqm** [comment]
you can use [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) as a workaround

**Comment by telmag92** [comment]
I am getting the same issue on macos
macOS Ventura 13.1
node version
16.19.0
yarn version
1.22.19
Expo version
6.1.0

**Comment by sunnylqm** [comment]
it can't be the same issue. please open a new issue and provide the error log. @telmag92

**Comment by saimehhh** [comment]
I have the same problem, and it is macos. How can I solve it

**Comment by marceljay** [comment]
Note:
`yarn --verbose` is not a valid command+flag for yarn berry v3+
