### ISSUE TITLE
[Question] walletconnect version

### ISSUE THREAD

**Issue by xylin-dev** [OneKeyHQ/app-monorepo#2201]
i used onekey to connect a dapp website, but after scanning the qr code, the website prompted "invalid address".
the website uses walletconnect of version 2.
i guess it's caused by the mismatch of walletconnect version.

**Comment by Nellyjay22** [comment]
> i used onekey to connect a dapp website, but after scanning the qr code, the website prompted "invalid address".
> 
> the website uses walletconnect of version 2.
> 
> i guess it's caused by the mismatch of walletconnect version.

**Comment by PatrickChoo** [comment]
OneKey currently only supports WalletConnect V1, and may support V2 in the future. 
Stay tuned! 😉

**Comment by qqqzhch** [comment]
The support for WalletConnect is on mobile, right? I don't see a link to WalletConnect in my PC wallet.

**Comment by qqqzhch** [comment]
> The support for WalletConnect is on mobile, right? I don't see a link to WalletConnect in my PC wallet.
I found it, but the menu doesn't specifically mention WalletConnect, which is not very easy to find.

**Comment by ByteZhang1024** [comment]
WalletConnect 2.0 is already supported.
