### ISSUE TITLE
【Question】：QuoteResponse中data字段内的数据含义是什么？What is the meaning of the data inside the 'data' field in QuoteResponse?

### ISSUE THREAD

**Issue by Toketec** [OneKeyHQ/app-monorepo#2214]
- 需求：在处理询价请求时，我得到了询价的返回数据，准备对他进行解析，来满足自己的计算需要和展示需要。同时想换成自己的询价服务以提高访问效率，我应该如何返回data中的数据？
- 代码出处：0x.ts中的 const data = res.data.data as QuoteResponse

- 在查询1个eth兑换相应的USDT时得到了一大段返回数据，部分截图如下：
![image](https://user-images.githubusercontent.com/44367138/208034235-41843e9e-c1e8-4847-a8a4-ed39b0ff52c9.png)

- 我想了解一下QuoteResponse中的'data'中返回的数据代表什么含义。（0x415565b0000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000dac17f958d2ee523a2206206994597c13d831ec70000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000000000000000000000000000000000004518a36b00000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000.........................）

APP版本：3.16.0

万分感谢~~~~~~Thanks~~~~~~

**Comment by kwoktung** [comment]
闪兑 是 有 0x.org 提供的。 https://docs.0x.org/0x-api-swap/api-references/get-swap-v1-quote.
data字段是 0x.org 给提供的交易数据。一般不去解析 data 的数据。因为不知道合约 ABI. 但是 你可以根据 Response 里面的 其他的字段，例如 buyAmount/sellAmount 等来展示你的信息
