### ISSUE TITLE
[BUG]: Display rate error on Swap & Bridge page.

### ISSUE THREAD

**Issue by zhongyiio** [OneKeyHQ/app-monorepo#2228]
**Prerequisites**
Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked to make sure that this issue has not already been filed
- [x] I've asked for help in the [OneKey Discord](https://discord.com/invite/onekey) before filing this issue.

**Describe the bug**
On the Swap & Bridge page, select the USDC - ETH trading pair, enter 1 ETH in the ETH box, and **Rate field display 1 USDC ≈ 1176 ETH** on the details page.

**To Reproduce**
1. Go to Swap & Bridge page
2. Input 1 on ETH box
3. See error on Rate field

**Expected behavior**
Rate: 1 ETH  ≈ 1176 UDDC

**Screenshots**
![image](https://user-images.githubusercontent.com/10026361/208305545-1aafb761-dc79-4e10-b7fa-b5cc7c7f4076.png)

**Desktop (please complete the following information):**
 - OS: iOS & macOS
 - Version: 3.22.0 (2022121467)

**Comment by revan-zhang** [comment]
Thanks for the feedback, we will fix this UI display issue ASAP, thanks!

**Comment by revan-zhang** [comment]
Hi @zhongyiio , this UI issue we have fixed at [v3.23.0](https://github.com/OneKeyHQ/app-monorepo/releases/tag/v3.23.0). Of course, this is an API return value issue related to display. We have also updated this logic on the server side, so your version should also take effect.
