### ISSUE TITLE
Adding Custom tokens

### ISSUE THREAD

**Issue by danieladebanjo55** [OneKeyHQ/app-monorepo#2244]
## Summary

您好，我作为开发人员遇到了问题，我想将我的自定义令牌添加到 onekey，但我找不到带有预设令牌列表的文件 (Hello i have an issue as a developer, I want to add my custom token to onekey but i cant find the file with the preset token list)

## Context
 I can’t add custom tokens to the token list of the source code of onekey

## Environment

* Operating System: MacOs
* App Version: 3

**Comment by revan-zhang** [comment]
Please using this link to submit a new token. [https://onekey.so](https://onekey.so)
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/18140164/208801671-8b91781d-145e-4823-b467-d0e59cd7e940.png">
