### ISSUE TITLE
[BUG]:

### ISSUE THREAD

**Issue by danieladebanjo55** [OneKeyHQ/app-monorepo#2285]
**Describe the bug**
I built both the debug and release apk files using ./gradlew assembleRelease command. But anytime i launch the app it crashes on launch, How can you help? @sunnylqm @loatheb

**Comment by Gmlogy** [comment]
Hi, have you solved it ? if yes please can you show me how ?

**Comment by revan-zhang** [comment]
Hi @danieladebanjo55 @Gmlogy

For the compilation process of all our platforms, we have corresponding CI tasks. You can refer to our CI tasks to compile. At the same time, we have some environment variables that need to be set in advance. It is best to set them on the expo platform.Or you can provide more detailed error and crash logs for us to analyze.
