### ISSUE TITLE
[BUG]: `src/hardware/OnekeyLite/types` could not be found within the package

### ISSUE THREAD

**Issue by danieladebanjo55** [OneKeyHQ/app-monorepo#2291]
**Describe the bug**
While resolving module `@onekeyhq/app/src/hardware/OnekeyLite/types`, the Haste package `@onekeyhq/app` was found. However the module<img width="701" alt="Screen Shot 2022-12-23 at 7 16 19 PM" src="https://user-images.githubusercontent.com/113938239/209447480-4a79f343-7921-4359-9f06-4923c3535c4a.png">. Indeed, none of these files exist:

  * `/Users/user/Downloads/working/app-monorepo/packages/app/src/hardware/OnekeyLite/types(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`

**Comment by sunnylqm** [comment]
Thanks for the catch. Just rename the `OnekeyLite/types.d.ts` to `OnekeyLite/types.ts`

**Comment by danieladebanjo55** [comment]
Thanks for the assist but now it gives me this error:
error While trying to resolve module `superstruct` from file `/Users/user/Downloads/working/app-monorepo/node_modules/@solana/web3.js/lib/index.browser.cjs.js`, the package `/Users/user/Downloads/working/app-monorepo/node_modules/superstruct/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/user/Downloads/working/app-monorepo/node_modules/superstruct/lib/index.cjs`. Indeed, none of these files exist:
<img width="699" alt="Screen Shot 2022-12-24 at 4 04 27 AM" src="https://user-images.githubusercontent.com/113938239/209455842-f948869b-9607-4ad1-bdee-6dfd61907936.png">
monorepo/node_modules/superstruct/lib/index.cjs(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
*appmonorepo/node_modules/superstruct/lib/index.cjs/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
Error: While trying to resolve module `superstruct` from file `/working/appmonorepo/node_modules/@solana/web3.js/lib/index.browser.cjs.js`, the package `/appmonorepo/node_modules/superstruct/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/app-monorepo/node_modules/superstruct/lib/index.cjs`. Indeed, none of these files exist:
