### ISSUE TITLE
[BUG]:Error: Generating a new Keystore is not supported in --non-interactive      mode

### ISSUE THREAD

**Issue by danieladebanjo55** [OneKeyHQ/app-monorepo#2298]
**Describe the bug**
Error: Generating a new Keystore is not supported in --non-interactive 
    mode

<img width="1001" alt="Screen Shot 2022-12-25 at 2 27 39 AM" src="https://user-images.githubusercontent.com/113938239/209488483-bff974dd-262a-4d5a-92a8-6727bdff565f.png">

I've been trying to solve this for hours now but i have not found a solution.kindly help out

**Comment by revan-zhang** [comment]
When running this command for the first time, you need to generate the corresponding keystore file in the console of Expo. You can execute it locally according to your account first, and then use CI to execute after ensuring that you have the keystore content.
