### ISSUE TITLE
I want to clone the project but getting issue while installing

### ISSUE THREAD

**Issue by mayank-techeniac** [OneKeyHQ/app-monorepo#2509]
**Prerequisites**

- [ ] I checked to make sure that this issue has not already been filed
- [ ] I've asked for help in the [OneKey Discord](https://discord.com/invite/onekey) before filing this issue.

**Describe the bug**
I downloaded the code and tried to follow the first step to install yarn dependencies in windows 11.

It throws the error as attached in the screenshot.

![image](https://user-images.githubusercontent.com/73283246/217171221-a34321c9-0101-4c4a-b150-8bfa53c73b4e.png)

Log:
# This file contains the result of Yarn building a package (@onekeyhq/app-monorepo@workspace:.)
# Script name: postinstall

'bash' is not recognized as an internal or external command,
operable program or batch file.
command not found: bash

**To Reproduce**
1. run command "yarn"

**Comment by sunnylqm** [comment]
please post the error log content in your screenshot

**Comment by mayank-techeniac** [comment]
> please post the error log content in your screenshot

edited description, please check

**Comment by sunnylqm** [comment]
because there are some bash scripts. you need a compatible environment to run these scripts (try wsl, git-bash, cygwin ...) or rewrite the script in bat format.

**Comment by mayank-techeniac** [comment]
okay will try that

**Comment by dhruvinp07** [comment]
> okay will try that

its working or not ?

i face same issue in my windows and i cant find solution
