### ISSUE TITLE
[Question] where is the project id of the walletconnect?

### ISSUE THREAD

**Issue by anatoly7778** [OneKeyHQ/app-monorepo#2540]
i cant find the project id of walletconnect. 
where to find it, to change it?

**Comment by sidmorizon** [comment]
walletconnect v2 not supported yet

**Comment by anatoly7778** [comment]
walletconnect will be shutting down all Cloud-hosted servers for v1.0 on 28 June 2023.

you have to upgrade .

**Comment by qqqzhch** [comment]
I just recently finished adding walletconnect v2 support to an mpc wallet
If you are testing walletconnect v2 locally, the project id can be registered on the official website https://cloud.walletconnect.com/sign-up

**Comment by sidmorizon** [comment]
walletconnect V2 is ready, you can check projectId from consts `WALLET_CONNECT_V2_PROJECT_ID`

https://github.com/OneKeyHQ/app-monorepo/blob/onekey/packages/kit/src/components/WalletConnect/walletConnectConsts.ts#L18
