### ISSUE TITLE
[Feature] Trying to install expo-dev-client for testing?

### ISSUE THREAD

**Issue by markaltmaier** [OneKeyHQ/app-monorepo#2591]
When I try to install expo-dev-client, and run yarn android I get errors.

To reproduce the problem, run yarn workspace @onekeyhq/app add expo-dev-client

And then try running for android or ios the build will not work.

I need expo-dev-client to test the app with better testing environement, specially if you're trying to test ios on non macOS system.

Is it possible to add this package and make the build work at the same time ?

**Comment by sunnylqm** [comment]
there are some known conflicts with this package (maybe fixed in newer expo version, but we haven't verified).
