### ISSUE TITLE
[Feature] Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [OneKeyHQ/app-monorepo#2636]
Please add support the Android 13 theme icons feature.

![Screenshot_2023-02-28-08-52-53-648_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/221761682-1ec09d79-02e0-49ac-8e04-89bebc559de6.jpg)

**Comment by PatrickChoo** [comment]
Roger. We will add adaptive icon in the next release.

**Comment by ByteZhang1024** [comment]
The next version supports.  🎉
https://github.com/OneKeyHQ/app-monorepo/pull/2639

**Comment by xmha97** [comment]
Thanks 🙏
