### ISSUE TITLE
Trojan-Downloader:W32/Kavala

### ISSUE THREAD

**Issue by Lyfebloc** [OneKeyHQ/app-monorepo#2725]
When running yarn install Trojan-Downloader:W32/Kavala tries to download. See screenshots [](url)
![Trojan Dectected](https://user-images.githubusercontent.com/107500172/225408325-c8775b3a-b404-4d60-b0bc-9f44334142aa.jpg)
![screenshot](https://user-images.githubusercontent.com/107500172/225409522-c9812057-934f-408a-8609-9467f443898f.jpg)

**Comment by sunnylqm** [comment]
What anti virus software are you using? It seems like a false positive.

**Comment by stackia** [comment]
After checking the source code of your mentioned package (`realm-network-transport` / `@realm.io/@common`), we believe this is a false positive.
