### ISSUE TITLE
[BUG]:iOS app can‘t import single private key of bitcoin

### ISSUE THREAD

**Issue by kirito41dd** [OneKeyHQ/app-monorepo#2755]
test it https://www.bitaddress.org:
1E6jFXWBCjKYpD1nrXK3enqpEUpx8SYcAy
Kz4q9nCZTLBmmd9c7ucpg9CnNG97jZSVuniQRWWhYpk9Ak4zcSC5

result: unsupport syntax

**Comment by originalix** [comment]
Thank you for your issue report. Our app currently only supports importing extended private keys for Bitcoin, and does not support importing single private keys. We apologize for any inconvenience this may have caused, and we will take your feedback into consideration for future updates.
