### ISSUE TITLE
build release android

### ISSUE THREAD

**Issue by Gmlogy** [OneKeyHQ/app-monorepo#2778]
Hi, i managed to build the source locally but i got this error

![image](https://user-images.githubusercontent.com/52473562/228210448-6763a727-f8a0-4ee4-bf6d-8ab0727b3355.png)

## Steps to Reproduce 
gradlew aR

## Environment

* Operating System: Windows 10
* App Version: 4.0.0

Please can you help! Thanks in advance

**Comment by ByteZhang1024** [comment]
We recommend that you use MacOS as your development platform.
> We have not made any adaptation to the windows development environment, unexpected problems may require you to solve yourself.

**Comment by Gmlogy** [comment]
i used MacOS but now i got another error related to webpack 

" Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema "
![Screen Shot 2023-03-30 at 05 00 50](https://user-images.githubusercontent.com/52473562/228734411-cc8f1984-7984-4981-9774-1928ce533239.png)

**Comment by sunnylqm** [comment]
what's your installed version of expo-cli? any version > 6.1.0 won't work

**Comment by Gmlogy** [comment]
Thanks it worked but i faced another Error i already spent many hours to find a solution, i really appreciate your help
![Screen Shot 2023-03-30 at 18 16 18](https://user-images.githubusercontent.com/52473562/228927963-ad75d9dc-1109-497b-b698-549bc4141014.png)

**Comment by Gmlogy** [comment]
Finally i solved it, but i don't know why the expo-image-picker and expo-intent-launcher prompt an error during the android build, i tried both debug and release the same result, please do you have any idea about how to fix this ?

![Screen Shot 2023-04-01 at 05 38 17](https://user-images.githubusercontent.com/52473562/229267854-2c6a5e85-956a-494c-afa7-e9801b4dc76d.png)

**Comment by Gmlogy** [comment]
Hey guys, Finally i solved the errors and the build finished successfully but when i launch it on device it crash after the splash screen, is this related to the .env variables ? is necessary to fill the var values or it's okay to leave it blank or maybe the crash caused by something else ?, Please provide some help

**Comment by sunnylqm** [comment]
You need to provide some logcat logs of the crash for us to analyze.

**Comment by Gmlogy** [comment]
![339382604_235795185693429_1899279971699479023_n](https://user-images.githubusercontent.com/52473562/230123018-e3cf5e97-dc59-4290-97df-79f95f1faf2c.jpeg)

**Comment by Gmlogy** [comment]
After cleaning the gradle i got this error in logcat

`9910 14574 E ReactNativeJS: Invariant Violation: Module RCTDeviceEventEmitter is not a registered callable module (calling emit). A frequent cause of the error is that the application entry file path is incorrect.`

`04-05 16:34:48.999 11881 14243 E ReactNativeJS: Invariant Violation: Module HMRClient is not a registered callable module (calling setup). A frequent cause of the error is that the application entry file path is incorrect.`

`04-05 16:34:48.999 11881 14243 E ReactNativeJS:       This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: v8`

`04-05 16:34:49.016 11881 14243 E ReactNativeJS: Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
04-05 16:34:49.016 11881 14243 E ReactNativeJS:       This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: v8
`

`04-05 16:34:49.042 11881 14243 E ReactNativeJS: Invariant Violation: Module JSTimers is not a registered callable module (calling callTimers). A frequent cause of the error is that the application entry file path is incorrect.
04-05 16:34:49.042 11881 14243 E ReactNativeJS:       This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: v8
`

**Comment by sunnylqm** [comment]
```A frequent cause of the error is that the application entry file path is incorrect.```

Are you using the latest codebase? What changes did you make?

**Comment by Gmlogy** [comment]
i'm using version 4.2.0, i didn't made any changes yet i'm just trying to build the app to see it on my phone

**Comment by sunnylqm** [comment]
how did you solve other errors you mentioned above?

**Comment by Gmlogy** [comment]
i removed this lines from development/copy-injected.sh to fix the yarn build, i guess web-embed module not required by the /app module
 
`# build and copy web-embed
if [ "$EAS_BUILD" == "true" ];
  then
    yarn workspace @onekeyhq/web-embed build
  elif [ ! -d "packages/web-embed/web-build" ]; then
    yarn workspace @onekeyhq/web-embed build
fi`

for the android build, i downgraded expo-image-picker to 13.1.1 and expo-intent-launcher to 10.2.0

**Comment by sunnylqm** [comment]
The web-embed module is required and we never met any issue with the expo modules.
Can you run `npx react-native info` in your project folder and paste the results here?

**Comment by Gmlogy** [comment]
![Screen Shot 2023-04-06 at 02 23 58](https://user-images.githubusercontent.com/52473562/230256565-d51ae3dc-e268-477f-920c-9fcd88c3af39.png)

`info Fetching system and libraries information...
System:
    OS: macOS 12.4
    CPU: (4) x64 Intel(R) Core(TM) i5-3470S CPU @ 2.90GHz
    Memory: 87.60 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.18.0 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
`

so i have to make the lines back for the web-embed in copy-injected.sh?

**Comment by sunnylqm** [comment]
yes i think web-embeded is a must and you should set yarn version to berry (i'll fix the readme later). and it's weird that the info does not include your xcode/android sdk version

**Comment by Gmlogy** [comment]
i already used yarn 3.3.1 in the first time but i got an error related to workspace @onekeyhq .... i used 1.18.0 and it worked, yes i don't know why xcode and android not showing on the infos, anyway i will use yarn berry as you suggest and i will try again

**Comment by Gmlogy** [comment]
Thank you for your time and your help ,it's working now
