### ISSUE TITLE
[BUG]:Network error screen on ios when creating a wallet

### ISSUE THREAD

**Issue by ArtemFlutterDev** [OneKeyHQ/app-monorepo#2877]
I'm archiving a TestFlight application through Xcode using a production environment.
After downloading via TestFlight, I create a wallet, on the Recovery Phrase screen, I click on "I saved the phrase" and instead of an animation with text, I see the "No connection" screen and the "Refresh" button does nothing.
However, if I close and open the application, I get to the wallet screen. 
The bug does not appear when I run the application in debug mode and does not appear on Android.

Please tell me what processes are running at this moment, which can give such an error.

![photo_5334567403218126098_y](https://user-images.githubusercontent.com/74657601/233351120-12a95332-2e4c-49cb-a0e2-977a5e9d1743.jpg)

**Comment by sunnylqm** [comment]
The animation is running inside a webview. Make sure you have built and bundled the `web-embeded` module when you are archiving.

**Comment by ArtemFlutterDev** [comment]
> The animation is running inside a webview. Make sure you have built and bundled the `web-embeded` module when you are archiving.
Issue solved. Thank you!
