### ISSUE TITLE
[Feature] Add Portfolio in homepage

### ISSUE THREAD

**Issue by Ridhubharan** [OneKeyHQ/app-monorepo#2884]
**Is your feature request related to a problem? Please describe.**
There is no way to display assets from different blockchains in a same page.

**Describe the solution you'd like**
Add portfolio in home page and aggregate the assets from different blockchains to have an overview.
Something like, 

![](https://www.softwaretestinghelp.com/wp-content/qa/uploads/2023/01/Uphold-Portfolio.png)

**Comment by rayston92** [comment]
Good advice!

**Comment by rayston92** [comment]
Exactly what I want @PatrickChoo

**Comment by oktay50000** [comment]
yes ,even on desktop app its good to see whole balance instead of switch ing chain

**Comment by stackia** [comment]
We added this feature (the "All Networks" page) in [v4.10.0](https://github.com/OneKeyHQ/app-monorepo/releases/tag/v4.10.0). Feel free to have a try!

<img width="1134" alt="image" src="https://github.com/OneKeyHQ/app-monorepo/assets/5107241/97bb5582-8ded-4290-b601-23fa95e35cb4">

**Comment by fajarsis** [comment]
Has this feature been released yet?
