### ISSUE TITLE
[BUG]:yarn clean 、yarn cache后重新yarn,无法完成依赖初始化：nvalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.  - configuration.node should be one of these:    false | object { __dirname?, __filename?, global? }    -> Include polyfills or mocks for various node stuff.    Details:     * configuration.node has an unknown property 'module'. These properties are valid:

### ISSUE THREAD

**Issue by Toketec** [OneKeyHQ/app-monorepo#2902]
感谢处理~~~
![image](https://user-images.githubusercontent.com/44367138/234580393-4357e6a8-b8cb-4b5c-b032-117d9dd2520e.png)
![image](https://user-images.githubusercontent.com/44367138/234580593-1e2b0095-5eda-4714-a857-47d5ee60f540.png)
yarn workspace @onekeyhq/web-embed build
$ rm -rf ./web-build && GENERATE_SOURCEMAP=false npx expo build:web && cp ./web-build/index.html ./web-build/404.html && sh ./postbuild.sh
============ webpack.version  4.46.0 web
Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.node should be one of these:
   false | object { __dirname?, __filename?, global? }
   -> Include polyfills or mocks for various node stuff.
   Details:
    * configuration.node has an unknown property 'module'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'dgram'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'dns'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'fs'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'http2'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'net'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'tls'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.
    * configuration.node has an unknown property 'child_process'. These properties are valid:
      object { __dirname?, __filename?, global? }
      -> Options object for node compatibility features.

**Comment by sunnylqm** [comment]
请检查expo-cli的版本`expo --version`，不能高于6.1.0

**Comment by Toketec** [comment]
> 请检查expo-cli的版本`expo --version`，不能高于6.1.0

thanks all~~~ i change the version to 6.0.8 and problem solved
