### ISSUE TITLE
[BUG]:更新xcode14.3后，重新编译ios客户端，出现编译失败。Yaga模块编译失败，是不是又是版本兼容的问题？

### ISSUE THREAD

**Issue by Toketec** [OneKeyHQ/app-monorepo#2910]
项目中reactnative版本是0.68.3
![image](https://user-images.githubusercontent.com/44367138/234769519-41421592-45d2-4dba-b835-ff686014cdbf.png)
![image](https://user-images.githubusercontent.com/44367138/234769554-d2edaf24-ffb7-4c09-a1f9-93225a76ba33.png)
› Compiling react-native Pods/Yoga » Yoga.cpp

❌  (../../node_modules/react-native/ReactCommon/yoga/yoga/Yoga.cpp:2232:9)

  2230 |         generationCount);
  2231 |     node->setLayoutHadOverflow(
> 2232 |         node->getLayout().hadOverflow() |
       |         ^ use of bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
  2233 |         currentRelativeChild->getLayout().hadOverflow());
  2234 |   }
  2235 |   return deltaFreeSpace;

› Compiling react-native Pods/Yoga » Yoga-dummy.m
› Packaging Pods/ZXingObjC » libZXingObjC.a
› Compiling react-native Pods/Yoga » YGValue.cpp
› Compiling react-native Pods/Yoga » YGStyle.cpp
› Compiling react-native Pods/Yoga » YGNodePrint.cpp
› Compiling react-native Pods/Yoga » YGNode.cpp
› Compiling react-native Pods/Yoga » YGLayout.cpp
› Compiling react-native Pods/Yoga » YGEnums.cpp
    Run script build phase '[CP-User] Generate app.config for prebuilt Constants.manifest' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'EXConstants' from project 'Pods')
    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'OneKeyWallet' from project 'OneKeyWallet')

› 1 error(s), and 2 warning(s)

Failed to build iOS project. "xcodebuild" exited with error code 65.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1

**Comment by sunnylqm** [comment]
你没有拉取最新代码
https://github.com/OneKeyHQ/app-monorepo/blob/onekey/patches/react-native%2B0.68.3.patch#L176-L186

**Comment by Toketec** [comment]
谢谢，新的补丁解决了问题
