### ISSUE TITLE
救急！！使用eas构建的时候，如何设置版本控制住6.1.0以内【请检查expo-cli的版本`expo --version`，不能高于6.1.0】

### ISSUE THREAD

**Issue by Toketec** [OneKeyHQ/app-monorepo#2914]
请检查expo-cli的版本`expo --version`，不能高于6.1.0

_Originally posted by @sunnylqm in https://github.com/OneKeyHQ/app-monorepo/issues/2902#issuecomment-1523460929_

**Comment by sunnylqm** [comment]
不太明白问题是什么，就指定版本安装啊？

**Comment by Toketec** [comment]
就是我想eas构建的时候指定使用某个版本的expocli，如图所示：sui'ra虽然我添加了配置，但是在安卓构建的时候依然没奏效，从而产生了web-embed构建失败的问题
我的配置改动：
![image](https://user-images.githubusercontent.com/44367138/234895085-3df9ed23-92c4-40a4-a913-99d66962bbe6.png)
报错：
![image](https://user-images.githubusercontent.com/44367138/234895380-f24bed54-c97a-4c49-8324-b32117b53bbb.png)
![image](https://user-images.githubusercontent.com/44367138/234895560-71341f4d-8741-4f69-867c-f82232a57680.png)

**Comment by sunnylqm** [comment]
![image](https://user-images.githubusercontent.com/615282/234896812-97de24d3-7747-4a31-b9ed-3a2e53bb762d.png)

**Comment by sunnylqm** [comment]
我看了下eas的文档，expoCli和env是并列的，也说明确实不在env下面
![image](https://user-images.githubusercontent.com/615282/234897069-4c1ca6fe-da4d-4567-8e71-66cedea78fa0.png)

**Comment by Toketec** [comment]
尝试使用这种方式配置后，expo识别到了版本，但是依然不能解决web-enbed编译问题：😭😭😭
配置写法：
![image](https://user-images.githubusercontent.com/44367138/235029699-9afdac25-fa2a-4928-a457-f7915d608258.png)

expo编译错误：
![image](https://user-images.githubusercontent.com/44367138/235029620-b838b92c-1914-4144-ab7d-dfc6ea42bf01.png)
![image](https://user-images.githubusercontent.com/44367138/235029756-2dfd28e3-a193-4b0c-ad29-2d4244a90057.png)
![image](https://user-images.githubusercontent.com/44367138/235029800-1c115656-5c1d-40e4-ac0c-98d254a42c33.png)

**Comment by ByteZhang1024** [comment]
看一下我们现有的方案。 https://docs.expo.dev/build-reference/npm-hooks/#packagejson-and-shell-script
"eas-build-pre-install": "bash ./scripts/eas-build-pre-install.sh"
build  前会重新安装指定版本 expo

**Comment by Toketec** [comment]
已解决
