### ISSUE TITLE
[BUG]:感谢救急❤️❤️，安卓构建依然有问题，似乎是 Gradle 构建任务app:copyReleaseBundledJs过程存在重复的资源文件。Expo项目我该怎么处理这个问题

### ISSUE THREAD

**Issue by Toketec** [OneKeyHQ/app-monorepo#2919]
> Task :app:copyReleaseBundledJs FAILED
[stderr] 
FAILURE: Build completed with 2 failures.
[stderr] 
1: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
Execution failed for task ':app:copyReleaseBundledJs'.
[stderr] 
> Entry assets/release/index.android.bundle is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.5.1/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
2: Task failed with an exception.
[stderr] 
-----------
[stderr] 
* What went wrong:
[stderr] 
java.lang.StackOverflowError (no error message)
[stderr] 
* Try:
[stderr] 
> Run with --stacktrace option to get the stack trace.
[stderr] 
> Run with --info or --debug option to get more log output.
[stderr] 
> Run with --scan to get full insights.
[stderr] 
==============================================================================
[stderr] 
* Get more help at https://help.gradle.org
[stderr] 
BUILD FAILED in 14m 41s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
1675 actionable tasks: 1675 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
报错：
![image](https://user-images.githubusercontent.com/44367138/235110671-718bc059-7605-4844-81c5-693c1b7d4a68.png)
GPT:
![image](https://user-images.githubusercontent.com/44367138/235114788-d42231b9-3212-47a3-901a-1137fad210c8.png)

**Comment by sunnylqm** [comment]
参考这里的构建步骤
https://github.com/OneKeyHQ/app-monorepo/blob/onekey/.github/workflows/release-android.yml

**Comment by ByteZhang1024** [comment]
可以参考一下代码, 自己适配一下。
https://github.com/OneKeyHQ/app-monorepo/blob/b7af6dd448379fefaa4a79a727fbf04a5c433725/patches/react-native+0.68.3.patch#L195-L206

**Comment by Toketec** [comment]
感谢~问题已解决，原因是新版换用了新的gradle和plugin，我还是用的之前的7.4.2+4.2.2，所以应该在patch中去掉对应的补丁
