### ISSUE TITLE
 ❤️thanks for helping !!苹果审核3.1.5和4.7条款被拒绝。贵公司有没有遇到类似情况，如何解决的。不会形成竞争，产品基于贵公司开源软件已经改动，但是保留了网页浏览器嵌入的Dapp引发了审核不通过。

### ISSUE THREAD

**Issue by Toketec** [OneKeyHQ/app-monorepo#2923]
求帮助~~~我们产品不会与您形成竞争，产品基于贵公司开源软件已经改动，但是保留了网页浏览器嵌入的Dapps可能引发了审核不通过。期望帮忙看看有没有遇到类似情况，如何顺利通过appstore审核。
![image](https://user-images.githubusercontent.com/44367138/235837299-e7068b13-4a5e-4de3-a1a7-03d12f288349.png)
![image](https://user-images.githubusercontent.com/44367138/235837424-dea2828c-d1ca-4d39-b6b6-a27d19a0685e.png)

**Comment by sunnylqm** [comment]
这个是比较灰色的地带，建议您仔细阅读代码，或是搜索类似情况如何处理

**Comment by rayston92** [comment]
Hi,

Regarding your question about Crypto payments and HTML5 pages, we recommend that you consult Apple's guidelines. 

Each Apple reviewer has different areas of focus, and it is important to analyze each issue on a case-by-case basis. 

Additionally, effective communication with Apple reviewers requires a thorough understanding of the context and the specifics of your business. 

Unfortunately, we are unable to assist with this issue.
