### ISSUE TITLE
What's the problem? How do you fix it，yarn android:device

### ISSUE THREAD

**Issue by jiangpnj** [OneKeyHQ/app-monorepo#2951]
┌──(root㉿kali)-[/opt/…/app-monorepo/packages/app/android]
└─# proxychains4 yarn android:device
[proxychains] config file found: /etc/proxychains4.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.15
[proxychains] DLL init: proxychains-ng 4.15
[proxychains] DLL init: proxychains-ng 4.15
[proxychains] DLL init: proxychains-ng 4.15
[proxychains] DLL init: proxychains-ng 4.15
[proxychains] DLL init: proxychains-ng 4.15
[proxychains] DLL init: proxychains-ng 4.15
[proxychains] DLL init: proxychains-ng 4.15
WARNING: expo-cli has not yet been tested against Node.js v18.13.0.
If you encounter any issues, please report them to https://github.com/expo/expo-cli/issues

expo-cli supports following Node.js versions:
* >=12.13.0 <15.0.0 (Maintenance LTS)
* >=16.0.0 <17.0.0 (Active LTS)

┌─────────────────────────────────────────────────────────────────────────┐
│                                                                         │
│   There is a new version of expo-cli available (6.3.7).                 │
│   You are currently using expo-cli 6.0.8                                │
│   Install expo-cli globally using the package manager of your choice;   │
│   for example: `npm install -g expo-cli` to get the latest version      │
│                                                                         │
└─────────────────────────────────────────────────────────────────────────┘
✔ Select a device/emulator › Pixel_6_Pro (device)
› Using --device Pixel_6_Pro
› Port 8081 is running @onekeyhq/app-monorepo in another window
  /opt/mymymy/projects/android/OneKeyHQ/app-monorepo (pid 5911)
✔ Use port 8082 instead? … yes
› Building app...
[proxychains] DLL init: proxychains-ng 4.15
[proxychains] DLL init: proxychains-ng 4.15
[proxychains] DLL init: proxychains-ng 4.15
[proxychains] DLL init: proxychains-ng 4.15
[proxychains] DLL init: proxychains-ng 4.15
[proxychains] DLL init: proxychains-ng 4.15
[proxychains] DLL init: proxychains-ng 4.15
[proxychains] DLL init: proxychains-ng 4.15
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Configuration on demand is an incubating feature.
[proxychains] DLL init: proxychains-ng 4.15
[proxychains] DLL init: proxychains-ng 4.15

> Configure project :app
App Version: 4.5.0
App Version Code: 1

defaultConfig whenTaskAdded
false

> Configure project :expo-application
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-av
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-barcode-scanner
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-camera
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-clipboard
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-constants
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-device
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-file-system
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-font
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-haptics
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-image-loader
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-image-manipulator
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-image-picker
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-intent-launcher
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-keep-awake
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-linear-gradient
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-local-authentication
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-localization
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-media-library
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-modules-core
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-notifications
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-secure-store
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo-splash-screen
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :expo

Using expo modules
  - expo-application (4.1.0)
  - expo-av (11.2.3)
  - expo-barcode-scanner (11.3.0)
  - expo-camera (12.2.0)
  - expo-clipboard (3.0.1)
  - expo-constants (13.1.1)
  - expo-device (4.3.0)
  - expo-file-system (14.0.0)
  - expo-font (10.1.0)
  - expo-haptics (11.2.0)
  - expo-image-loader (3.2.0)
  - expo-image-manipulator (10.4.0)
  - expo-image-picker (13.1.1)
  - expo-intent-launcher (10.2.0)
  - expo-keep-awake (10.1.1)
  - expo-linear-gradient (11.3.0)
  - expo-local-authentication (12.2.0)
  - expo-localization (13.0.0)
  - expo-media-library (14.1.0)
  - expo-modules-core (0.9.2)
  - expo-notifications (0.15.4)
  - expo-secure-store (11.2.0)
  - expo-splash-screen (0.15.1)
  - react-native-v8$expo (1.6.0)

WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :lottie-react-native
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :react-native-firebase_analytics
:react-native-firebase_analytics package.json found at /opt/mymymy/projects/android/OneKeyHQ/app-monorepo/node_modules/@react-native-firebase/analytics/package.json
:react-native-firebase_app package.json found at /opt/mymymy/projects/android/OneKeyHQ/app-monorepo/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_analytics:firebase.bom using custom value: 29.2.1
:react-native-firebase_analytics package.json found at /opt/mymymy/projects/android/OneKeyHQ/app-monorepo/node_modules/@react-native-firebase/analytics/package.json
:react-native-firebase_analytics:version set from package.json: 14.12.0 (14,12,0 - 14012000)
:react-native-firebase_analytics:android.compileSdk using custom value: 33
:react-native-firebase_analytics:android.targetSdk using custom value: 33
:react-native-firebase_analytics:android.minSdk using custom value: 23
:react-native-firebase_analytics:reactNativeAndroidDir /opt/mymymy/projects/android/OneKeyHQ/app-monorepo/node_modules/react-native/android

> Configure project :react-native-firebase_app
:react-native-firebase_app package.json found at /opt/mymymy/projects/android/OneKeyHQ/app-monorepo/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_app:firebase.bom using custom value: 29.2.1
:react-native-firebase_app:play.play-services-auth using default value: 20.3.0
:react-native-firebase_app package.json found at /opt/mymymy/projects/android/OneKeyHQ/app-monorepo/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_app:version set from package.json: 14.12.0 (14,12,0 - 14012000)
:react-native-firebase_app:android.compileSdk using custom value: 33
:react-native-firebase_app:android.targetSdk using custom value: 33
:react-native-firebase_app:android.minSdk using custom value: 23
:react-native-firebase_app:reactNativeAndroidDir /opt/mymymy/projects/android/OneKeyHQ/app-monorepo/node_modules/react-native/android

> Configure project :react-native-firebase_crashlytics
:react-native-firebase_crashlytics package.json found at /opt/mymymy/projects/android/OneKeyHQ/app-monorepo/node_modules/@react-native-firebase/crashlytics/package.json
:react-native-firebase_app package.json found at /opt/mymymy/projects/android/OneKeyHQ/app-monorepo/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_crashlytics:firebase.bom using custom value: 29.2.1
:react-native-firebase_crashlytics package.json found at /opt/mymymy/projects/android/OneKeyHQ/app-monorepo/node_modules/@react-native-firebase/crashlytics/package.json
:react-native-firebase_crashlytics:version set from package.json: 14.12.0 (14,12,0 - 14012000)
:react-native-firebase_crashlytics:android.compileSdk using custom value: 33
:react-native-firebase_crashlytics:android.targetSdk using custom value: 33
:react-native-firebase_crashlytics:android.minSdk using custom value: 23
:react-native-firebase_crashlytics:reactNativeAndroidDir /opt/mymymy/projects/android/OneKeyHQ/app-monorepo/node_modules/react-native/android

> Configure project :react-native-firebase_perf
:react-native-firebase_perf package.json found at /opt/mymymy/projects/android/OneKeyHQ/app-monorepo/node_modules/@react-native-firebase/perf/package.json
:react-native-firebase_app package.json found at /opt/mymymy/projects/android/OneKeyHQ/app-monorepo/node_modules/@react-native-firebase/app/package.json
:react-native-firebase_perf:firebase.bom using custom value: 29.2.1
:react-native-firebase_perf package.json found at /opt/mymymy/projects/android/OneKeyHQ/app-monorepo/node_modules/@react-native-firebase/perf/package.json
:react-native-firebase_perf:version set from package.json: 14.12.0 (14,12,0 - 14012000)
:react-native-firebase_perf:android.compileSdk using custom value: 33
:react-native-firebase_perf:android.targetSdk using custom value: 33
:react-native-firebase_perf:android.minSdk using custom value: 23
:react-native-firebase_perf:reactNativeAndroidDir /opt/mymymy/projects/android/OneKeyHQ/app-monorepo/node_modules/react-native/android

> Configure project :react-native-flipper
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

> Configure project :react-native-reanimated
No AAR for react-native-reanimated found. Attempting to build from source.
Android gradle plugin: 7.3.1
Gradle: 7.5.1
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.

FAILURE: Build failed with an exception.

* Where:
Build file '/opt/mymymy/projects/android/OneKeyHQ/app-monorepo/node_modules/react-native-v8/android/build.gradle' line: 21

* What went wrong:
A problem occurred evaluating project ':react-native-v8'.
> findNodePackageDir() execution failed - nodeCommand[node --print require.resolve('react-native/package.json')]
  [proxychains] DLL init: proxychains-ng 4.15
  [proxychains] DLL init: proxychains-ng 4.15

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 5s
6 actionable tasks: 6 up-to-date
/opt/mymymy/projects/android/OneKeyHQ/app-monorepo/packages/app/android/gradlew exited with non-zero code: 1
Error: /opt/mymymy/projects/android/OneKeyHQ/app-monorepo/packages/app/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at spawnAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnGradleAsync (/usr/local/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:83:28)
    at assembleAsync (/usr/local/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:57:16)
    at actionAsync (/usr/local/lib/node_modules/expo-cli/src/commands/run/android/runAndroid.ts:145:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by sunnylqm** [comment]
node > 16 is not tested and most likely not supported
