### ISSUE TITLE
[BUG]: Installing Dependency Failed

### ISSUE THREAD

**Issue by danieladebanjo55** [OneKeyHQ/app-monorepo#3004]
**Describe the bug**
Tried installing the dependencies using ''yarn", but wasn't successful.

**To Reproduce**
1. Clone the repo
2. install dependencies using 'Yarn'

**Screenshots**
<img width="1118" alt="Screen Shot 2023-05-20 at 5 06 35 PM" src="https://github.com/OneKeyHQ/app-monorepo/assets/113938239/e0c607a5-bb13-49ff-8b32-021e4dd63eda">

**ERROR MESSAGE:**
➤ YN0009: │ @onekeyhq/app-monorepo@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /private/var/folders/l3/_1y0g1z931b1701k5fyky35c0000gn/T/xfs-17defaf5/build.log)

build.log [file](https://drive.google.com/file/d/1ZcFBVIhmIvGG0KL2IokNGqlMgWtpvV4J/view?usp=share_link) 

**Additional context**
node v16.0.0 (npm v9.6.6)
yarn 3.3.1
Operating System: MacOS

**Comment by sunnylqm** [comment]
npm i -g expo-cli@6.1.0

**Comment by danieladebanjo55** [comment]
Thanks
