### ISSUE TITLE
[Feature] Allow separate sites connections per wallet

### ISSUE THREAD

**Issue by mtsh1000** [OneKeyHQ/app-monorepo#3015]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Community & Quick support**

- [Community Forum](https://github.com/orgs/OneKeyHQ/discussions). Best for: help with building, discussion about best practices.
- [Discord](https://discord.gg/onekey). Best for: sharing your ideas and hanging out with the community.

**Additional context**

**Comment by revan-zhang** [comment]
Currently our wallet already supports this feature. Thanks.
