### ISSUE TITLE
[BUG]:Issue with yarn install

### ISSUE THREAD

**Issue by ArtemFlutterDev** [OneKeyHQ/app-monorepo#3169]
Node: 16.16
Yarn: 3.5.0
OS: MacOS

After cloning the repository and making all instructions I do `yarn` and get an error - **console-feed@npm:3.4.1: The remote server failed to provide the requested resource.**

<img width="621" alt="image" src="https://github.com/OneKeyHQ/app-monorepo/assets/74657601/fa929c9f-c975-4b04-b23e-5546daa735c5">

**Comment by ByteZhang1024** [comment]
Please follow the console-feed.
https://github.com/samdenty/console-feed/issues/124

**Comment by ByteZhang1024** [comment]
fixed
