### ISSUE TITLE
[Question]我想了解onekey在通过助记词创建钱包时是如何确保应用正常运行的，因为我在RN上使用bip39的mnemonicToSeedSync会卡死好几秒

### ISSUE THREAD

**Issue by Vvaraz** [OneKeyHQ/app-monorepo#3175]
您好，我是rn项目的新手，最近尝试使用rn来制作一个钱包应用，我试着用之前web使用的bip39和ethersjs来生成种子，但是在安卓上整个应用会卡住几秒钟无法操作。我看到贵项目也是使用bip39来生成种子。不知道能否提供下解决卡顿的方法，只有思路也可以。感谢！

**Comment by ByteZhang1024** [comment]
We have not encountered may not be able to help you.
