### ISSUE TITLE
Problem with yarn. Webpack issue 

### ISSUE THREAD

**Issue by ArtemFlutterDev** [OneKeyHQ/app-monorepo#3180]
Node: 16.16
Yarn: 3.5.0
OS: MacOS

Steps to reproduce:
- Clone project
- npm i -g expo-cli@6.1.0
- yarn

I saw a solved issue like that here but installing expo-cli@6.1.0 gives no effect.
Could you check it, please?

<img width="791" alt="image" src="https://github.com/OneKeyHQ/app-monorepo/assets/74657601/90358ffd-56f9-4baf-8574-3513f5894870">

Log file ->  [build.log](https://github.com/OneKeyHQ/app-monorepo/files/11935639/build.log)

**Comment by ByteZhang1024** [comment]
Which is commit?

**Comment by ArtemFlutterDev** [comment]
> Which is commit?

Latest

**Comment by Flashnas** [comment]
Any advice for this issue? @ByteZhang1024 @sunnylqm

**Comment by sunnylqm** [comment]
try run `expo --version` and `which expo` and paste the results here

**Comment by ArtemFlutterDev** [comment]
> try run `expo --version` and `which expo` and paste the results here

himars@Artems-Air app-monorepo-onekey 2 % expo --version         
6.3.9
himars@Artems-Air app-monorepo-onekey 2 % which expo             
/opt/homebrew/bin/expo

**Comment by sunnylqm** [comment]
i dont understand how you got expo installed in homebrew (a package happen to have the same name in homebrew? but what is that?) and the version is clearly not what we expect.
try `rm /opt/homebrew/bin/expo` then run again

**Comment by ArtemFlutterDev** [comment]
> i dont understand how you got expo installed in homebrew (a package happen to have the same name in homebrew? but what is that?) and the version is clearly not what we expect. try `rm /opt/homebrew/bin/expo` then run again

Ok now it is the correct version but still got an issue when `yarn clean` and `yarn`.

himars@Artems-Air app-monorepo-onekey 2 % expo --version           
6.1.0
himars@Artems-Air app-monorepo-onekey 2 % which expo               
/usr/local/bin/expo

**Comment by sunnylqm** [comment]
what's the new issue

**Comment by ArtemFlutterDev** [comment]
> what's the new issue

The same 
<img width="690" alt="image" src="https://github.com/OneKeyHQ/app-monorepo/assets/74657601/b8be7447-8c9a-47a8-b8f3-f293dca58c62">

log file - [build.log](https://github.com/OneKeyHQ/app-monorepo/files/12002862/build.log)

**Comment by sunnylqm** [comment]
Did you check the expo version and path **before** and **after** you run yarn in the **same** terminal tab/window?
I suspect there are still other globally installed `expo-cli`s via other package managers (i am still wondering how can you install expo in homebrew?)

**Comment by lokiikoll** [comment]
Why not add expo-cli@6.0.8 to devDependencies?
@sunnylqm

**Comment by sunnylqm** [comment]
because it needs to be executed as a global cli

**Comment by ByteZhang1024** [comment]
It was closed without further problems.
