### ISSUE TITLE
[BUG]: expo-cli version 6.0.8 is no longer supported

### ISSUE THREAD

**Issue by markaltmaier** [OneKeyHQ/app-monorepo#3193]
This version of expo-cli is not supported anymore.
It's highly recommended to update to the newest version.
The API endpoints used in this version of expo-cli might not exist,
any interaction with Expo servers may result in unexpected behaviour.

current project expo-cli@6.0.8 version as recommended is no longer supported.

Do I need to upgrade expo-cli to the latest or ignore this warning ?

**Comment by ByteZhang1024** [comment]
The amount of migration work is very large, and I did not find the relevant expo documentation to explain this problem.

**Comment by ByteZhang1024** [comment]
See the warning. Thanks for the warning.
