### ISSUE TITLE
[BUG]: app crashes when calling resetApp method in packages/kit-bg/src/services/ServiceApp.ts

### ISSUE THREAD

**Issue by markaltmaier** [OneKeyHQ/app-monorepo#3218]
appVersion: 4.9.0
OS: Tested on IOS and Android

Both when calling reset app the app crashes, but it should restart like old version

To reproduce.

Got to >> menu >> Reset App

The app crashes, checked logs, no errors is shown?

**Comment by ByteZhang1024** [comment]
It was turned off on purpose, as expected.
