### ISSUE TITLE
Assets not seen after adding all networks![BUG]:

### ISSUE THREAD

**Issue by amazingHuo** [OneKeyHQ/app-monorepo#3232]
![image](https://github.com/OneKeyHQ/app-monorepo/assets/17975200/db3034c7-172f-4271-8cce-3371f4ba02c8)

**Comment by ByteZhang1024** [comment]
Features are still under development.

**Comment by amazingHuo** [comment]
> Features are still under development.

When is it expected to be developed?

**Comment by ByteZhang1024** [comment]
Some server parts need to be deployed.
So need to wait for the next version, about seven business days.
