### ISSUE TITLE
[BUG]: Displays inaccurate and unfriendly status when loading the token price chart

### ISSUE THREAD

**Issue by lokiikoll** [OneKeyHQ/app-monorepo#3245]
**Describe the bug**

When loading the token price chart (especially for the first time), it initially displays a "No Data" UI, which is not accurate because the data is being loaded at this time, and the loading UI should be displayed. Moreover, the "No Data" UI does not match the overall UI style.

**To Reproduce**

1. Open or reopen the OneKey App
2. Click on a coin, for example, Ethereum
3. Seeing the "No Data" UI.

**Expected behavior**

A loading UI should be displayed before the data request returns a result.
Or simply display a horizontal line.

**Screenshots**

![482873197543](https://github.com/OneKeyHQ/app-monorepo/assets/10759236/c10664d4-fd38-4e78-b535-53be8aba55e2)

**Smartphone :**
 - Device: iPhone XR
 - OS: 16.1.1
 - Version 4.9.1-2023070786

**Comment by stackia** [comment]
Hi @lokiikoll, thanks for reporting! We just created an internal ticket (OK-22597) to track this. I'll update here once we have added the loading UI.

**Comment by sidmorizon** [comment]
fixed https://github.com/OneKeyHQ/app-monorepo/pull/3438
