### ISSUE TITLE
[Question]Need assistance with injecting Ethereum object and establishing connection between RN wallet app and Dapp

### ISSUE THREAD

**Issue by Vvaraz** [OneKeyHQ/app-monorepo#3255]
Hey, everyone:

I’m currently using RN to design wallet apps, but I’m unsure where to begin with the dapp browser. I’m not sure how to inject the Ethereum object for Dapp usage nor how to establish a connection between my app and the Dapp when it connects to the wallet. I was wondering if you could provide me with some solutions or relevant resources. I’m feeling really frustrated and overwhelmed.

**Comment by ByteZhang1024** [comment]
Our implementation is relatively complex, you can refer to Metamask.

[BackgroundBridge](https://github.com/MetaMask/metamask-mobile/blob/main/app/core/BackgroundBridge/BackgroundBridge.js)
[BrowserTab](https://github.com/MetaMask/metamask-mobile/blob/main/app/components/Views/BrowserTab/index.js)

**Comment by Vvaraz** [comment]
Ok, thank you very much
