### ISSUE TITLE
[BUG]:Error when yarn android

### ISSUE THREAD

**Issue by ArtemFlutterDev** [OneKeyHQ/app-monorepo#3402]
Environment:
- java: java 11.0.19 2023-04-18 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.19+9-LTS-224)
- yarn: 3.5.0
- node: v16.16.0
- expo: 6.1.0 (which expo: /usr/local/bin/expo)
After cloning the project I do:
- yarn 
- npm install -g expo-cli@6.1.0
- yarn android

Then I receive this error 
`Error at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:700:9)
    at Object.spawn [as default] (/usr/local/lib/node_modules/expo-cli/node_modules/cross-spawn/index.js:12:24)
    at /usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:34:18
    at new Promise (<anonymous>)
    at spawnAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:31:17)
    at adbAlreadyRunning (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/Android.ts:277:36)
    at getAdbOutputAsync (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/Android.ts:295:34)
    at getAttachedDevicesAsync (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/Android.ts:206:18)
    at Object.getAllAvailableDevicesAsync (/usr/local/lib/node_modules/expo-cli/node_modules/xdl/src/Android.ts:97:25)`

**Comment by stackia** [comment]
Could you check if you have all the Android development tooling set up and make sure `adb` is available in your PATH?

https://reactnative.dev/docs/next/environment-setup?guide=native&platform=android

**Comment by ArtemFlutterDev** [comment]
> Could you check if you have all the Android development tooling set up and make sure `adb` is available in your PATH?
> 
> https://reactnative.dev/docs/next/environment-setup?guide=native&platform=android

I did all the instructions from this link, now with yarn android configuration bar already starts and then executing bar but it crashes with this error:
 Task :app:createBundleDirectDebugJsAndAssets FAILED
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: std::__1::system_error: open: /Users/himars/Downloads/app-monorepo-onekey/packages/kit: Operation not permitted
    at BunserBuf.<anonymous> (/Users/himars/Downloads/app-monorepo-onekey/node_modules/fb-watchman/index.js:95:23)
    at BunserBuf.emit (node:events:527:28)
    at BunserBuf.process (/Users/himars/Downloads/app-monorepo-onekey/node_modules/bser/index.js:292:10)
    at /Users/himars/Downloads/app-monorepo-onekey/node_modules/bser/index.js:247:12
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
Emitted 'error' event on WatchmanWatcher instance at:
    at Client.<anonymous> (/Users/himars/Downloads/app-monorepo-onekey/node_modules/metro-file-map/src/watchers/WatchmanWatcher.js:107:12)
    at Client.emit (node:events:527:28)
    at BunserBuf.<anonymous> (/Users/himars/Downloads/app-monorepo-onekey/node_modules/fb-watchman/index.js:107:12)
    at BunserBuf.emit (node:events:527:28)
    at /Users/himars/Downloads/app-monorepo-onekey/node_modules/bser/index.js:249:12
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  watchmanResponse: {
    error: 'std::__1::system_error: open: /Users/himars/Downloads/app-monorepo-onekey/packages/kit: Operation not permitted',
    version: '2023.08.14.00'
  }
}

> Task :expo-modules-core:compileDebugKotlin
w: Argument -Xopt-in is deprecated. Please use -opt-in instead
w: file:///Users/himars/Downloads/app-monorepo-onekey/node_modules/expo-modules-core/android/src/main/java/expo/modules/adapters/react/permissions/PermissionsService.kt:157:30 'getPackageInfo(String, Int): PackageInfo!' is deprecated. Deprecated in Java
w: file:///Users/himars/Downloads/app-monorepo-onekey/node_modules/expo-modules-core/android/src/main/java/expo/modules/core/utilities/EmulatorUtilities.kt:30:13 'SERIAL: String!' is deprecated. Deprecated in Java
w: file:///Users/himars/Downloads/app-monorepo-onekey/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/Promise.kt:68:18 This declaration overrides deprecated member but not marked as deprecated itself. This deprecation won't be inherited in future releases. Please add @Deprecated annotation or suppress. See https://youtrack.jetbrains.com/issue/KT-47902 for details
w: file:///Users/himars/Downloads/app-monorepo-onekey/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/activityresult/ActivityResultsManager.kt:52:24 Parameter 'activity' is never used
w: file:///Users/himars/Downloads/app-monorepo-onekey/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/activityresult/AppContextActivityResultRegistry.kt:119:51 'getParcelableExtra(String!): T?' is deprecated. Deprecated in Java
w: file:///Users/himars/Downloads/app-monorepo-onekey/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/activityresult/AppContextActivityResultRegistry.kt:180:26 'getParcelable(String?): T?' is deprecated. Deprecated in Java
w: file:///Users/himars/Downloads/app-monorepo-onekey/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/activityresult/AppContextActivityResultRegistry.kt:271:83 'getParcelable(String?): T?' is deprecated. Deprecated in Java
w: file:///Users/himars/Downloads/app-monorepo-onekey/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/activityresult/DataPersistor.kt:67:20 'getSerializable(String?): Serializable?' is deprecated. Deprecated in Java
w: file:///Users/himars/Downloads/app-monorepo-onekey/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/activityresult/DataPersistor.kt:85:26 'getSerializable(String?): Serializable?' is deprecated. Deprecated in Java
w: file:///Users/himars/Downloads/app-monorepo-onekey/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/events/KModuleEventEmitterWrapper.kt:90:7 'constructor Event<T : Event<(raw) Event<*>>!>(Int)' is deprecated. Deprecated in Java
w: file:///Users/himars/Downloads/app-monorepo-onekey/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/jni/JavaScriptObject.kt:59:33 Parameter 'null' is never used
w: file:///Users/himars/Downloads/app-monorepo-onekey/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/jni/JavaScriptObject.kt:100:5 Parameter 'null' is never used
w: file:///Users/himars/Downloads/app-monorepo-onekey/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/modules/Module.kt:43:7 'coroutineScope: CoroutineScope' is deprecated. Use a scope from the AppContext
w: file:///Users/himars/Downloads/app-monorepo-onekey/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/Either.kt:24:11 Parameter 'type' is never used
w: file:///Users/himars/Downloads/app-monorepo-onekey/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/Either.kt:27:11 Parameter 'type' is never used
w: file:///Users/himars/Downloads/app-monorepo-onekey/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/Either.kt:44:11 Parameter 'type' is never used
w: file:///Users/himars/Downloads/app-monorepo-onekey/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/Either.kt:59:11 Parameter 'type' is never used
w: file:///Users/himars/Downloads/app-monorepo-onekey/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/types/JSTypeConverterHelper.kt:44:17 'get(String!): Any?' is deprecated. Deprecated in Java
w: file:///Users/himars/Downloads/app-monorepo-onekey/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewManagerDefinitionBuilder.kt:125:30 'ViewGroupDefinitionLegacyBuilder' is deprecated. Use `ViewGroupDefinitionBuilder` instead.
w: file:///Users/himars/Downloads/app-monorepo-onekey/node_modules/expo-modules-core/android/src/main/java/expo/modules/kotlin/views/ViewManagerDefinitionBuilder.kt:128:38 'ViewGroupDefinitionLegacyBuilder' is deprecated. Use `ViewGroupDefinitionBuilder` instead.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:createBundleDirectDebugJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 3m 39s
1157 actionable tasks: 1152 executed, 5 up-to-date
/Users/himars/Downloads/app-monorepo-onekey/packages/app/android/gradlew exited with non-zero code: 1
Error: /Users/himars/Downloads/app-monorepo-onekey/packages/app/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (node:events:642:26)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    ...
    at spawnAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnGradleAsync (/usr/local/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:83:28)
    at assembleAsync (/usr/local/lib/node_modules/expo-cli/src/commands/run/android/spawnGradleAsync.ts:57:16)
    at actionAsync (/usr/local/lib/node_modules/expo-cli/src/commands/run/android/runAndroid.ts:145:22)

**Comment by stackia** [comment]
Please try moving the entire project out of the `Downloads` directory. macOS put strict permission restrictions on `Downloads` / `Documents` / etc.
