### ISSUE TITLE
[BUG]: Developing on Windows failed

### ISSUE THREAD

**Issue by dp77** [OneKeyHQ/app-monorepo#3404]
I'm encountering the same problem as described in [this link](https://github.com/OneKeyHQ/app-monorepo/issues/2509) when I try to run this code on my Windows operating system. I'm having trouble finding a solution for this error. Any help would be appreciated.

**Comment by huhuanming** [comment]
Because there are some bash scripts.

You might want to consider giving WSL a try. In case you encounter any further issues, it would be greatly appreciated if you could share the relevant logs.

**Comment by stackia** [comment]
Developing on Windows is currently not supported (because React Native has poor support on Windows). You may try on WSL but there are probably many issues. But I believe as long as you are only working with the web & ext app, the build script should work on WSL.

**Comment by dp77** [comment]
![image](https://github.com/OneKeyHQ/app-monorepo/assets/111431434/be4584c4-48d7-4181-a44d-197930319c2a)

[xfs-15754a29.log](https://github.com/OneKeyHQ/app-monorepo/files/12366396/xfs-15754a29.log)
[xfs-ce2c3c79.log](https://github.com/OneKeyHQ/app-monorepo/files/12366400/xfs-ce2c3c79.log)

Thank you for your response! I'm currently encountering two errors within the WSL.

**Comment by dp77** [comment]
![image](https://github.com/OneKeyHQ/app-monorepo/assets/111431434/be4584c4-48d7-4181-a44d-197930319c2a)

[xfs-15754a29.log](https://github.com/OneKeyHQ/app-monorepo/files/12366396/xfs-15754a29.log)
[xfs-ce2c3c79.log](https://github.com/OneKeyHQ/app-monorepo/files/12366400/xfs-ce2c3c79.log)

Thank you for your response! I'm currently encountering two errors within the WSL.

**Comment by dp77** [comment]
> ![image](https://user-images.githubusercontent.com/111431434/261224479-be4584c4-48d7-4181-a44d-197930319c2a.png)
> 
> [xfs-15754a29.log](https://github.com/OneKeyHQ/app-monorepo/files/12366396/xfs-15754a29.log) [xfs-ce2c3c79.log](https://github.com/OneKeyHQ/app-monorepo/files/12366400/xfs-ce2c3c79.log)
> 
> Thank you for your response! I'm currently encountering two errors within the WSL.

@stackia @huhuanming

**Comment by stackia** [comment]
What is your nodejs version? Try upgrading to the latest LTS version

**Comment by dp77** [comment]
> What is your nodejs version? Try upgrading to the latest LTS version

I updated from version 18.17.0 to 18.17.1, but the problem still exist.

**Comment by sidmorizon** [comment]
try node version `16.*.*` 

https://github.com/OneKeyHQ/app-monorepo/blob/onekey/package.json#L7

**Comment by dp77** [comment]
> try node version `16.*.*`
> 
> https://github.com/OneKeyHQ/app-monorepo/blob/onekey/package.json#L7

![image](https://github.com/OneKeyHQ/app-monorepo/assets/111431434/f5bf769d-758b-4f47-849c-58327d1480c0)

[build.log](https://github.com/OneKeyHQ/app-monorepo/files/12519844/build.log)

I've tried this version already, but I keep facing errors in all versions.
