### ISSUE TITLE
[BUG]:Dependencies blake2b & blake2b-wasm 404 [tag 3.16]

### ISSUE THREAD

**Issue by metanomad21** [OneKeyHQ/app-monorepo#3425]
My project was forked from tag 3.16 and it was fine just a month ago
When I remove the dependency, re-execute yarn and msg shows that 
https://github.com/BitGo/blake2b and
https://github.com/BitGo/blake2b-wasm
are not found

env:
macOS 13.4 
nodejs 16
yarn 1.18

error:
yarn install v1.18.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning Resolution field "metro-react-native-babel-preset@0.70.0" is incompatible with requested version "metro-react-native-babel-preset@~0.67.0"
warning Resolution field "@solana/web3.js@1.47.3" is incompatible with requested version "@solana/web3.js@^1.53.0"
warning Resolution field "react-native-qrcode-svg@6.1.2" is incompatible with requested version "react-native-qrcode-svg@6.0.6"
warning Resolution field "react-native-svg@12.3.0" is incompatible with requested version "react-native-svg@9.6.4"
warning Resolution field "metro-react-native-babel-preset@0.70.0" is incompatible with requested version "metro-react-native-babel-preset@0.67.0"
warning Resolution field "metro-react-native-babel-preset@0.70.0" is incompatible with requested version "metro-react-native-babel-preset@~0.64.0"
warning Resolution field "metro-react-native-babel-preset@0.70.0" is incompatible with requested version "metro-react-native-babel-preset@0.67.0"
[3/5] 🚚  Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/BitGo/blake2b
Directory: /Users/9purpledao/workspace/app/9-purple-app
Output:
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by ByteZhang1024** [comment]
The version is too old, and you need to try to fix it yourself.
