### ISSUE TITLE
[BUG]: Cannot Connect to any Aptos DApp

### ISSUE THREAD

**Issue by SamuelQZQ** [OneKeyHQ/app-monorepo#3437]
**Prerequisites**
Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked to make sure that this issue has not already been filed
- [x] I've asked for help in the [OneKey Discord](https://discord.com/invite/onekey) before filing this issue.

**Describe the bug**
OneKey cannot connect to Aptos DApp. 
The error in console is:
```
Uncaught (in promise) window.petra.getNetwork is not a function
```

**To Reproduce**
Go to any Aptos DApp, install both OneKey and Petra. Then connect Petra. It will fail.
It works before.

**Expected behavior**
Connect successfully.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ByteZhang1024** [comment]
You have both OneKey and Petra installed?
You can try disabling Petra and turning on the Petra option in Wallet Switch.

<img width="380" alt="image" src="https://github.com/OneKeyHQ/app-monorepo/assets/92281880/625e0365-1f7a-4ed8-a187-b25a30aa26f0">
<img width="379" alt="image" src="https://github.com/OneKeyHQ/app-monorepo/assets/92281880/afe23340-b2e1-4f0a-a209-0e634a79713c">

**Comment by ByteZhang1024** [comment]
If there is a problem, open it or start an order in Discord.
