### ISSUE TITLE
changing the feeRecipient or removing cn.etherscan.com doesn't seem to do anything[BUG]:

### ISSUE THREAD

**Issue by wolfer21** [OneKeyHQ/app-monorepo#3443]
Hi there, I tried changing the feeRecipient address and tried to remove the cn.etherscan.com block explorer so to only have etherscan.io, tried yarn clean and rebuilding but nothing changed when clicking on the buttons that brings you to etherscan, and the feeRecipient also doesn't seem to change. Also I'm not sure about what this API endpoint does: https://api.onekeycn.com/api, can we change or remove it? can we create our own APIs? Thank you!

**Comment by sidmorizon** [comment]
https://api.onekeycn.com/api is the server side for the wallet. This part of the code is not open source. If you wish to modify or remove it, you may need to study the client code and make the necessary adjustments yourself.
