### ISSUE TITLE
[BUG]: Wallet buttons don't work on Samsung Galaxy s23 Ultra

### ISSUE THREAD

**Issue by wolfer21** [OneKeyHQ/app-monorepo#3457]
![screenshot2](https://github.com/OneKeyHQ/app-monorepo/assets/55052782/dca391a6-c4bb-4917-81c1-3137b5e75052)
These buttons do not work on Samsung galaxy s23 ultra with Android 13 and One UI 5.1, sometimes one of them works after pressing many many times, but 99% of the times they don't work. Works fine on other android devices and iOS.

**Comment by ByteZhang1024** [comment]
We have fixed the issue, but we need to wait until next week's release.

**Comment by ByteZhang1024** [comment]
It has been published and is awaiting review by various platforms.
