### ISSUE TITLE
[BUG]: building apk with expo fails

### ISSUE THREAD

**Issue by wolfer21** [OneKeyHQ/app-monorepo#3513]
When trying to run an android build with expo, it always fails with the following error: 

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.

-----------

* What went wrong:

Execution failed for task ':lib-keys-secret:configureCMakeRelWithDebInfo[arm64-v8a]'.

> [CXX1409] /home/expo/workingdir/build/packages/app/android/lib-keys-secret/.cxx/RelWithDebInfo/142n145q/arm64-v8a/android_gradle_build.json release|arm64-v8a : expected buildFiles file 'C:\Users\LAZZARO\Documents\ICO-Dapps\wallet-swap\packages\app\android\lib-keys-secret\src\main\cpp\CMakeLists.txt' to exist

* Try:

> Run with --stacktrace option to get the stack trace.

> Run with --info or --debug option to get more log output.

> Run with --scan to get full insights.

==============================================================================

2: Task failed with an exception.

-----------

* What went wrong:

java.lang.StackOverflowError (no error message)

* Try:

> Run with --stacktrace option to get the stack trace.

> Run with --info or --debug option to get more log output.

> Run with --scan to get full insights.

==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 7m 18s

I did not edit the codebase, only regenerated the keystore, changed the EAS project id and connected my expo account.

I ran the build with: eas build --profile=production --platform android

**Comment by ByteZhang1024** [comment]
There's no more information. It's not enough to find out what the problem is.

**Comment by wolfer21** [comment]
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.

-----------

* What went wrong:

Execution failed for task ':lib-keys-secret:buildCMakeRelWithDebInfo[arm64-v8a]'.

> com.android.ide.common.process.ProcessException: ninja: Entering directory `/home/expo/workingdir/build/packages/app/android/lib-keys-secret/.cxx/RelWithDebInfo/142n145q/arm64-v8a'

  [1/3] Building C object CMakeFiles/keys.dir/keys.c.o

  FAILED: CMakeFiles/keys.dir/keys.c.o 

  /home/expo/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android23 --sysroot=/home/expo/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot -Dkeys_EXPORTS  -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fexceptions -O2 -g -DNDEBUG -fPIC -fvisibility=hidden -MD -MT CMakeFiles/keys.dir/keys.c.o -MF CMakeFiles/keys.dir/keys.c.o.d -o CMakeFiles/keys.dir/keys.c.o -c /home/expo/workingdir/build/packages/app/android/lib-keys-secret/src/main/cpp/keys.c

  /home/expo/workingdir/build/packages/app/android/lib-keys-secret/src/main/cpp/keys.c:18:57: error: use of undeclared identifier 'authorizedAppSha1'

      if (checkSecurityPermission(env, context, (char **) authorizedAppSha1, 3)) {

                                                          ^

  /home/expo/workingdir/build/packages/app/android/lib-keys-secret/src/main/cpp/keys.c:19:16: warning: implicit declaration of function 'getDecryptedKey' is invalid in C99 [-Wimplicit-function-declaration]

          return getDecryptedKey(env, liteInitGPCParams, sizeof(liteInitGPCParams));

                 ^

  /home/expo/workingdir/build/packages/app/android/lib-keys-secret/src/main/cpp/keys.c:19:63: error: use of undeclared identifier 'liteInitGPCParams'

          return getDecryptedKey(env, liteInitGPCParams, sizeof(liteInitGPCParams));

                                                                ^

  /home/expo/workingdir/build/packages/app/android/lib-keys-secret/src/main/cpp/keys.c:19:37: error: use of undeclared identifier 'liteInitGPCParams'

          return getDecryptedKey(env, liteInitGPCParams, sizeof(liteInitGPCParams));

                                      ^

  1 warning and 3 errors generated.

  [2/3] Building C object CMakeFiles/keys.dir/validation.c.o

ninja: build stopped: subcommand failed.

  
  C++ build system [build] failed while executing:

      /home/expo/Android/Sdk/cmake/3.22.1/bin/ninja \

        -C \

        /home/expo/workingdir/build/packages/app/android/lib-keys-secret/.cxx/RelWithDebInfo/142n145q/arm64-v8a \


        keys


    from /home/expo/workingdir/build/packages/app/android/lib-keys-secret
    
    after clearing the gradle build, it build locally but not with expo, giving me these arrors about CMake

**Comment by wolfer21** [comment]
I also noticed that the keys.secret file is missing

**Comment by ByteZhang1024** [comment]
Delete this section of code and try again.
 https://github.com/OneKeyHQ/app-monorepo/issues/2047#issuecomment-1325911413

**Comment by ByteZhang1024** [comment]
It was closed without further problems.
