### ISSUE TITLE
[BUG]: yarn android and build issue

### ISSUE THREAD

**Issue by wolfer21** [OneKeyHQ/app-monorepo#3541]
When building the app for android, I'm getting the same issue as described here: https://github.com/OneKeyHQ/app-monorepo/issues/2877

While trying yarn android, both on emulator and a real device, I always get this error when trying to open the app: 
![image](https://github.com/OneKeyHQ/app-monorepo/assets/55052782/1825f0a5-31a1-41ff-ae31-24860ee52474)

In console I get this error even though the build is succesful: 

> Configure project :react-native-reanimated
No AAR for react-native-reanimated found. Attempting to build from source.
Android gradle plugin: 7.4.2
Gradle: 7.5.1
WARNING:Software Components will not be created automatically for Maven publishing from Android Gradle Plugin 8.0. To opt-in to the future behavior, set the Gradle property android.disableAutomaticComponentCreation=true in the `gradle.properties` file or use the new publishing DSL.
<============-> 95% EXECUTING [49s]                                                                                                                                       
> :react-native-reanimated:assertNoMultipleInstances
> IDLE
> :react-native-gesture-handler:assertNoMultipleInstances
> :react-native-v8:buildCMakeRelWithDebInfo[x86][v8executor]
> IDLE
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: EPERM: operation not permitted, lstat 'C:\Users\...\...\...\app-monorepo\node_modules\react-native-v8\android\build\intermediates\cxx\RelWithDebInfo\6s463d65\obj\x86\libv8executor.so.tmp6b629c5'
Emitted 'error' event on NodeWatcher instance at:
    at C:\Users\...\...\...\app-monorepo\node_modules\metro-file-map\src\watchers\NodeWatcher.js:231:14 {
<============-> 95% EXECUTING [51s]
  code: 'EPERM',
  
> Task :app:kaptGenerateStubsDirectDebugKotlin
'compileDirectDebugJavaWithJavac' task (current target is 11) and 'kaptGenerateStubsDirectDebugKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
By default will become an error since Gradle 8.0+! Read more: https://kotl.in/gradle/jvm/target-validation
Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain (onekey)

I'm using openjdk version "11.0.20" and node v16.16.0.

**Comment by CCP-2FaceMonkey** [comment]
I am getting the similar issue with gradle version 7.4.2
![Screenshot 2023-10-04 at 11 00 50](https://github.com/OneKeyHQ/app-monorepo/assets/4448405/6a55a256-7d7a-4bd2-85b2-5b80e141ae63)
