### ISSUE TITLE
[BUG]:

### ISSUE THREAD

**Issue by socratese** [OneKeyHQ/app-monorepo#3559]
**Prerequisites**
Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ y] I checked to make sure that this issue has not already been filed
- [ y] I've asked for help in the [OneKey Discord](https://discord.com/invite/onekey) before filing this issue.

**Describe the bug**

when installing:

➤ YN0001: │   Repository URL: https://github.com/BitGo/blake2b.git
➤ YN0001: │   Remote Error: Repository not found.
➤ YN0001: │   Fatal Error: repository 'https://github.com/BitGo/blake2b.git/' not found
➤ YN0001: │   Exit Code: 128
➤ YN0000: └ Completed in 6s 543ms
➤ YN0000: Failed with errors in 6s 548ms

**To Reproduce**
1) pull latest
2) install

**Expected behavior**
fails at yarn install

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS Ventura 13.2]
 - Browser [safari]
 - Version [onekey development latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rayston92** [comment]
Thanks @socratese for providing the context.

@sidmorizon plz take a look at this issue.
