### ISSUE TITLE
[BUG]: 资产总和现实错误

### ISSUE THREAD

**Issue by ganwennl** [OneKeyHQ/app-monorepo#3612]
我主要是使用mac和ios。

发现在ios版和mac本中，defi的资产和代币会出现重合的现象，导致资产不准确。

比如bsc链中，在venus中质押的资产，选择所有网络，会出现vbtc等资产，导致资产叠加，实际只有一半。

**Comment by tredondo** [comment]
Thank you for posting that lazy issue with your cryptic username. Confirms that OneKey is not to be trusted.

**Comment by ByteZhang1024** [comment]
资产统计的问题，我们在逐步优化。

**Comment by ByteZhang1024** [comment]
> Thank you for posting that lazy issue with your cryptic username. Confirms that OneKey is not to be trusted.

The user is talking about asset statistics, and our statistical assets are still being gradually improved. @tredondo
