### ISSUE TITLE
[BUG]:Error when yarn desktop

### ISSUE THREAD

**Issue by YuHuaifeng** [OneKeyHQ/app-monorepo#3641]
Environment:

yarn: 3.6.4.0
node: v18.18.1
After cloning the project I do:
npm install -g expo-cli@6.1.0
yarn
yarn desktop
Then I receive this error
![1697182232063](https://github.com/OneKeyHQ/app-monorepo/assets/145749911/600f5a33-e254-4300-861c-758794d73d35)
![1697182410897](https://github.com/OneKeyHQ/app-monorepo/assets/145749911/c2b5d677-884c-47e8-a8df-e4be4a86c496)

**Comment by ByteZhang1024** [comment]
Our latest code does not need to install expo-cli separately, you can uninstall it and try it.

**Comment by YuHuaifeng** [comment]
> Our latest code does not need to install expo-cli separately, you can uninstall it and try it.

I reinstalled node.js and yarn on the new Ubuntu system(20.04.06 LTS) and downloaded the latest code. But this situation has arisen.And in the end, there were still errors in the questioning.In the same environment, it can run successfully on another PC.
![a98681f70fd59df673cc0e76e4af1cd](https://github.com/OneKeyHQ/app-monorepo/assets/145749911/0e02933c-ba1b-4cb8-a41e-15c38afa8d0f)

**Comment by YuHuaifeng** [comment]
> Our latest code does not need to install expo-cli separately, you can uninstall it and try it.


And in the end, there were still errors in the questioning

**Comment by ByteZhang1024** [comment]
You can try yarn clean, our latest code no longer requires a separate installation of expo-cli.
I haven't encountered the problem you mentioned.
