### ISSUE TITLE
[BUG]:yarn ios报错

### ISSUE THREAD

**Issue by weixiaojian001** [OneKeyHQ/app-monorepo#3655]
JSGlobalContextSetInspectable (../../node_modules/react-native/ReactCommon/jsc/JSCRuntime.cpp:402:7)

  400 |   #ifdef TARGET_OS_MAC
  401 |     if (__builtin_available(macOS 13.3, iOS 16.4, tvOS 16.4, *)) {
> 402 |       JSGlobalContextSetInspectable(ctx_, true);
      |       ^ use of undeclared identifier 'JSGlobalContextSetInspectable'; did you mean 'JSGlobalContextSetName'?
  403 |     }
  404 |   #endif
  405 |   #endif
  (../../node_modules/react-native/ReactCommon/jsc/JSCRuntime.cpp:402:43)

  400 |   #ifdef TARGET_OS_MAC
  401 |     if (__builtin_available(macOS 13.3, iOS 16.4, tvOS 16.4, *)) {
> 402 |       JSGlobalContextSetInspectable(ctx_, true);
      |                                           ^ cannot initialize a parameter of type 'JSStringRef' with an rvalue of type 'bool'
  403 |     }
  404 |   #endif
  405 |   #endif

**Comment by ByteZhang1024** [comment]
Look at this.
https://github.com/OneKeyHQ/app-monorepo/issues/3207#issuecomment-1627901794

**Comment by weixiaojian001** [comment]
> Look at this. [#3207 (comment)](https://github.com/OneKeyHQ/app-monorepo/issues/3207#issuecomment-1627901794)

  (/Users/xj/Desktop/code/githubwallet/app-monorepo/packages/app/ios/Pods/boost/boost/container_hash/hash.hpp:131:33)

  129 | #else
  130 |         template <typename T>
> 131 |         struct hash_base : std::unary_function<T, std::size_t> {};
      |                                 ^ no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
  132 | #endif

**Comment by ByteZhang1024** [comment]
You can try reinstalling it.
```
yarn ios-install
// or
cd packages/app/ 
pod install
```

**Comment by weixiaojian001** [comment]
> yarn ios-install

Is there any other method that doesn't work

**Comment by ByteZhang1024** [comment]
```yarn clean``` and remove app-monorepo/packages/app/iOS/Pods folder, Try again ```yarn``` or .

**Comment by weixiaojian001** [comment]
> `yarn clean` and remove app-monorepo/packages/app/iOS/Pods folder, Try again `yarn` or .

At first, I encountered this problem
 use of undeclared identifier 'JSGlobalContextSetInspectable'; did you mean 'JSGlobalContextSetName'
Upgrade related system environments.  macos 14.0  xcode 15.0
Another problem has arisen
 no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'
yarn ios-install
// or
cd packages/app/ ios
pod install
or yarn clean
None of it works

**Comment by ByteZhang1024** [comment]
It's so new that you need to manually downgrade it to Xcode 14.3
