### ISSUE TITLE
[Feature]How to get the address

### ISSUE THREAD

**Issue by weixiaojian001** [OneKeyHQ/app-monorepo#3691]
I want to get the wallet address by passing in the net and mnemonic words. Which method can I call?

**Comment by ByteZhang1024** [comment]
There is no direct way to call it, but you can refer to it.

https://github.com/OneKeyHQ/app-monorepo/blob/61de211585c78b572301216b4f2d198b6cbf4632/packages/engine/src/index.ts#L691
