### ISSUE TITLE
[Feature]Importing Bitcoin private key reports error: The private key is incorrect.

### ISSUE THREAD

**Issue by weixiaojian001** [OneKeyHQ/app-monorepo#3712]
When I enter the private key exported by onekey to import, it is correct. When I enter the private key exported by bitkeep or other wallets to import the private key, I get the error that the private key is incorrect. However, this private key can be imported and used in other wallets.

**Comment by ByteZhang1024** [comment]
You can give an example.
1. Create a new Demo mnemonic.
2. OneKey exported which network and what steps exported the private key.
3. which network other wallets are exported from and what steps are taken to export the private key.
4. what are the steps for import verification.
5. provide the Demo's private key and specific mnemonic.

You need to be clear for me to help you.

**Comment by weixiaojian001** [comment]
> You can give an example.
> 
> 1. Create a new Demo mnemonic.
> 2. OneKey exported which network and what steps exported the private key.
> 3. which network other wallets are exported from and what steps are taken to export the private key.
> 4. what are the steps for import verification.
> 5. provide the Demo's private key and specific mnemonic.
> 
> You need to be clear for me to help you.

L1TQWAn1eevpFJfDpwRqGLtXpdy72Hqt2jeryaJomcpqZApA5kCD
This is the Bitcoin private key I exported from bitkeep
This Bitcoin private key can be imported into Bitcoin wallets normally in other wallets
Select this private key in onekey to import the private key. Select Bitcoin to report an error.
![image](https://github.com/OneKeyHQ/app-monorepo/assets/38640468/4d9527e7-2996-43a9-ac50-cbdb846e1eb7)

**Comment by ByteZhang1024** [comment]
Currently OneKey does not support the import of BTC WIF (starts with 5) and WIF compressed (starts with L or K) private keys.

**Comment by weixiaojian001** [comment]
> Currently OneKey does not support the import of BTC WIF (starts with 5) and WIF compressed (starts with L or K) private keys.

Will support be added later?

**Comment by ByteZhang1024** [comment]
Not yet, but maybe later.
