### ISSUE TITLE
CORS Error While Running Latest Code on Localhost

### ISSUE THREAD

**Issue by dp77** [OneKeyHQ/app-monorepo#3732]
<img width="581" alt="Screenshot 2023-10-28 at 3 22 21 PM" src="https://github.com/OneKeyHQ/app-monorepo/assets/111431434/dd3f34b3-887d-47fd-a188-47af57b2f7bb">

When I run the latest release code on my localhost. I'm getting a CORS error on the website. I tried using a proxy, but the error persists. What should I do?

**Comment by ByteZhang1024** [comment]
The solution will be given later.

**Comment by markaltmaier** [comment]
For now just disable web security in your browser while testing

To do so

**linux --** `google-chrome  --user-data-dir=”/var/tmp/Chrome” --disable-web-security`
**windows** -- `"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disable-web-security --user-data-dir="D:\chrome"`
**OS x --** `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --disable-web-security --user-data-dir="<some-dir>"`

**Comment by dp77** [comment]
It's worked but I need a permanent solution for the production

**Comment by ByteZhang1024** [comment]
Related colleagues are still discussing the plan due to security concerns.
Wait patiently 🙇

**Comment by huhuanming** [comment]
Thank you very much for your feedback. You can try to execute `yarn app:web:proxy` or `yarn app:ext:proxy` on Web platform.
