### ISSUE TITLE
[BUG]: Local build on macOS Sonoma give me error

### ISSUE THREAD

**Issue by markaltmaier** [OneKeyHQ/app-monorepo#3755]
I use the following OS specs

macOS Sonoma
version: 14.1
Commnad Line tools: Xcode 15.0.1

And I use OneKey version 4.14.0

The error is as follows in pods

```
⚠️  ld: ignoring duplicate libraries: '-lc++'
❌  duplicate symbol '__ZN5folly19makeConversionErrorENS_14ConversionCodeENS_5RangeIPKcEE' in
┌─ libFlipper-Folly.a[30](Conv.o)
└─ libRCT-Folly.a[3](Conv.o)

❌  duplicate symbol '__ZN5folly6detail11str_to_boolEPNS_5RangeIPKcEE' in
┌─ libFlipper-Folly.a[30](Conv.o)
└─ libRCT-Folly.a[3](Conv.o)

› Executing OneKeyWallet » Bundle React Native code and images
› Executing OneKeyWallet » [CP] Copy Pods Resources

❌  error: Cycle inside OneKeyWallet; building could produce unreliable results.
```

This error is related to Xcode latest version [Build fails for Xcode 15](https://github.com/facebook/react-native/issues/37748)

Any sugessions on how to fix this problem?

**Comment by ByteZhang1024** [comment]
There are still some issues with Xcode 15 and Xcode 14 needs to be downgraded.

**Comment by markaltmaier** [comment]
@ByteZhang1024 Yes I've downgraded to `Xcode 14.3.1` and it works fine.
