### ISSUE TITLE
[Feature] All Networks doesn't allow many networks to be added (e.g. Kaspa)

### ISSUE THREAD

**Issue by perkmeister** [OneKeyHQ/app-monorepo#3756]
**Is your feature request related to a problem? Please describe.**
All Networks doesn't allow many networks to be added (e.g. Kaspa)

**Describe the solution you'd like**
The ability to see any defined set of networks at the same time so that a porfolio overview can be created. Currently we need to select individual networks, many networks cannot be added to the All Networks account.

**Comment by ByteZhang1024** [comment]
Can you be more specific? It would be nice to have a sketch.

**Comment by fajarsis** [comment]
Has this feature being released yet?

**Comment by ByteZhang1024** [comment]
The new version is being refactored and there is no estimated time.
