### ISSUE TITLE
[bug] init error

### ISSUE THREAD

**Issue by johnchenyan** [OneKeyHQ/app-monorepo#3759]
**CODE**：

`import HardwareSDK from '@onekeyfe/hd-common-connect-sdk';

(async () => {

  HardwareSDK.init({
    debug: true
  })

  const devices = await HardwareSDK.searchDevices()
  console.log(devices)

})()`

**ERROR**

` HardwareSDK.init({
              ^

TypeError: HardwareSDK.init is not a function
    at file:///Users/qc/antel/onekey/test/index.js:5:15
    at file:///Users/qc/antel/onekey/test/index.js:12:3
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)

Node.js v20.2.0`

**Comment by ByteZhang1024** [comment]
A minimum reproducible demo can be provided.

**Comment by johnchenyan** [comment]
I currently have a onekey classic that uses a usb connects to my macbook
How do I initialize on macbook  and search for devices
Can you provide a demo

**Comment by ByteZhang1024** [comment]
Then how did you repeat the problem.
There is no specific process steps or demo.

**Comment by johnchenyan** [comment]
> import HardwareSDK from '@onekeyfe/hd-common-connect-sdk';
> 
> const settings = {
>     env: 'lowlevel',
>     debug: true
>   }
> 
> HardwareSDK.init(settings)


Run the above code

**Comment by ByteZhang1024** [comment]
Direct node running?
Let me try.

**Comment by johnchenyan** [comment]
Yes，have a better way ？We just want to call the filecoin signed method

**Comment by ByteZhang1024** [comment]
You can try this demo.
https://github.com/OneKeyHQ/hardware-js-sdk/tree/onekey/packages/connect-examples/expo-example
