### ISSUE TITLE
希望可以增加全部网络的网络数量

### ISSUE THREAD

**Issue by hahayihao** [OneKeyHQ/app-monorepo#3767]
希望可以增加全部网络的网络数量
[目前不支持所有网络的选择]

![Screenshot_2023-11-07-03-13-04-76_381e071ac66b667d1c0b3dc99e0b933b](https://github.com/OneKeyHQ/app-monorepo/assets/47918781/b498fe8c-0351-4adb-8261-77534363117d)
![IMG_20231107_032144](https://github.com/OneKeyHQ/app-monorepo/assets/47918781/e9b60bfb-f3b2-4fa4-8b8f-8e86c5ce1635)

**Comment by ByteZhang1024** [comment]
这个功能正在考虑重新实现，可以期待一下。
