### ISSUE TITLE
[BUG]: yarn ios:device stuck at loading from metro / bundling 100%

### ISSUE THREAD

**Issue by markaltmaier** [OneKeyHQ/app-monorepo#3797]
connecting my iphone 12 ,os version 17 in development mode to macOS Ventura using xcode 14.2 and running the command

`yarn ios:device` or `npx expo run:ios --device`

the application gets stuck at **bundling 100%** or if I closed the app and opened it again it's stuck at **loading from metro**

Why is this happneing and is it only for my iphone or it happens to others ?

**Comment by ByteZhang1024** [comment]
iOS 17 is not currently supported
