### ISSUE TITLE
[BUG]: using @bitgo/utxo-lib to support a special type of transaction (coin base transaction type 5)

### ISSUE THREAD

**Issue by markaltmaier** [OneKeyHQ/app-monorepo#3800]
**OneKeyWallet[1428] <Error>: Unhandled JS Exception: ReferenceError: Can't find variable: WebAssembly**

I don't know why **WebAssembly** causes crashes on ios devices but not on android ?

I'm trying to implement `@bitgo/utxo-lib` to resolve the below problem related to Onekey Wallet

BitcoinJs lib doesn't support a special type of transaction (coin base transaction tye 5 >> rewards transactions) for coins like (dash)

Bitgo lib is a BitcoinJs wraper to enable support for such coins.
This lib was importable in previous Onekeys version (before 4.12.0) but in the latest updates (after 4.11.0)
It works for android but crashes on ios devices.

This is the link for the wraper.

[@bitgo/utxo-lib](https://github.com/BitGo/BitGoJS)

**Comment by ByteZhang1024** [comment]
We have upgraded Expo 49, React Native, and Webpack5. We have not used the libraries you mentioned. You can debug them yourself.

https://github.com/OneKeyHQ/app-monorepo/compare/v4.11.0...v4.15.0

**Comment by ByteZhang1024** [comment]
I haven't used this library and I'm not quite sure why.

**Comment by markaltmaier** [comment]
@ByteZhang1024

BitcoinJs lib doesn't support a special type of transaction **(coin base transaction tye 5 >> rewards transactions)** for coins like **(dash)**

Bitgo lib is a BitcoinJs wraper to enable support for such coins.
This lib was importable in previous Onekeys version (before 4.12.0) but in the latest updates (after 4.11.0)
It works for android but crashes on ios devices.

This is the link for the wraper.

[@bitgo/utxo-lib](https://github.com/BitGo/BitGoJS)

**Comment by markaltmaier** [comment]
@ByteZhang1024 **can you modify the lable to feature requested instead of help wanted**

The problem was in a package inside `@bitgo/utxo-lib` that it uses called `@bitgo/blake2b-wasm`

This library uses **WebAssembly** which causes crash on ios devices in production build

My solution was to go inside `yarn.lock` file and downgrade it's version to `"@bitgo/blake2b-wasm@npm:^3.2.0"`

This solved the problem, but I still have no idea why **WebAssembly** causes crashes on ios devices but not on android?

**Comment by ByteZhang1024** [comment]
The current support for WebAssembly is somewhat odd, and we all try not to use WebAssembly.

**Comment by ByteZhang1024** [comment]
We had no plan to deal with this issue and shut it down without any other issues.

**Comment by markaltmaier** [comment]
@ByteZhang1024 Yeah thank you for your suuport I'll close this issue as it's not related to this project, thank you for all your help
