### ISSUE TITLE
[Feature] expo requires an upgrade for node version used in build

### ISSUE THREAD

**Issue by markaltmaier** [OneKeyHQ/app-monorepo#3826]
Effective November 27, 2023, the default Node version will be upgraded from 16 to 18.

This build uses the default Node version, which is currently v16.18.1. It will change to v18.18.0 on the effective date. [Learn more](https://expo.dev/changelog/2023/11-03-node-default).

**Should I update this code in `package.json` to `node 18` instead?**

```
"engines": {
    "node": "^16.0.0"
  },
```

**Comment by ByteZhang1024** [comment]
Of course, node18 is currently working properly.

**Comment by markaltmaier** [comment]
@ByteZhang1024 The warning still exists in expo even after I updated the engine > node to ^18 

Then did yarn clean >> then yarn and uploaded build to expo through eas commands, the warning still exists.

![Screenshot from 2023-11-18 18-28-25](https://github.com/OneKeyHQ/app-monorepo/assets/72730763/3e4e3a95-2bd6-4f34-96ab-88d1f8690506)

**Comment by ByteZhang1024** [comment]
EAS image problem, you can manually modify it.

[ubuntu-22.04-jdk-11-ndk-r21e (alias default)](https://docs.expo.dev/build-reference/infrastructure/#ubuntu-2204-jdk-11-ndk-r21e-alias-default)

**Comment by ByteZhang1024** [comment]
Shut it down without any further questions.

**Comment by markaltmaier** [comment]
@ByteZhang1024
Sadly if you updated the image in eas.json to `"image": "macos-ventura-13.6-xcode-15.0"` 
This will give an error related to xcode 15 >>

```
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.0.sdk/usr/include/c++/v1/__config:836:53: note: expanded from macro '_LIBCPP_DEPRECATED_'
#      define _LIBCPP_DEPRECATED_(m) __attribute__((deprecated(m)))
```
```
❌  (/Users/expo/workingdir/build/packages/app/ios/Pods/boost/boost/container_hash/hash.hpp:131:33)

  129 | #else
  130 |         template <typename T>
> 131 |         struct hash_base : std::unary_function<T, std::size_t> {};
      |                                 ^ no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
  132 | #endif
```

These errors is related to xcode-15 which is currently not supported by OneKey project.

And expo will require an upgrade to the image to use the latest node-18.18.0 version.

How can I solve this issue ?

**Comment by ByteZhang1024** [comment]
No plans at the moment, we are actively maintaining Branch x.
