### ISSUE TITLE
[BUG]: build android locally using ./gradlew assembleDirectRelease always outputs the first build after yarn

### ISSUE THREAD

**Issue by markaltmaier** [OneKeyHQ/app-monorepo#3827]
using this command to build android locally `./gradlew assembleDirectRelease` always give the 1st build after yarn

so if I ran this command `yarn android `for debugging and then modified the code, then ran the above command ,the output will be as if I ran the code for the 1st build.

so I have to use yarn clean, and then yarn again to build the workspaces then run the above command `./gradlew assembleDirectRelease` which is un-effecient local build env.

Specially for android sometimes we don't need to use expo build.

I had to remove these folders every time before I run above command

```
rm -rf ./packages/app/android/.gradle
rm -rf ./packages/app/android/build
rm -rf ./packages/app/android/app/build
```

**Comment by ByteZhang1024** [comment]
It's a strange question. It needs to be tested.
