### ISSUE TITLE
[BUG]: typo in locale key `model__` should be `modal__`

### ISSUE THREAD

**Issue by friedger** [OneKeyHQ/app-monorepo#3840]
**Describe the bug**
As a developer, I am confused because two keys in locale folder starts with `model__` but are used in modal similar to keys with `modal__`

**To Reproduce**
See https://github.com/OneKeyHQ/app-monorepo/blob/onekey/packages/components/src/locale/en-US.json#L2136 
or search for `model__`

**Expected behavior**
keys used for locale text should be consistent.

**Additional context**
I would like to learn about the process of internationalization.

**Comment by ByteZhang1024** [comment]
Typo, thanks for the correction.
Internationalization is usually done by machine translation and manual verification.

**Comment by friedger** [comment]
@ByteZhang1024 Does it make sense to send a PR with changes to all locale files? Or do you have other files with all the keys?

**Comment by ByteZhang1024** [comment]
All the source files for translation are on Lokalise, so after submitting a PR, you also need to make changes on Lokalise.
Currently, the source code already includes all the translations, including the keys.
I'll check how external collaboration can help complete the translations and will reply later.

**Comment by ByteZhang1024** [comment]
If you have a need to modify the entry, we can add you to Lokalise, directly modify it. Let me know if you're interested.

**Comment by ByteZhang1024** [comment]
Call me if you have any ideas. issue is closed.
