### ISSUE TITLE
[Feature] App build in DNS query encryption

### ISSUE THREAD

**Issue by shikiroot** [OneKeyHQ/app-monorepo#3841]
I don’t know if the developers have noticed that all OneKey DNS records have been polluted in Mainland China. This not only causes all OneKey RPC nodes are unavailable, but may also bring other security risks. So I want to know if it is possible to add DNS query encryption in the app?

**Comment by ByteZhang1024** [comment]
Thanks for the feedback. I'll think about it later.

**Comment by ByteZhang1024** [comment]
At present, internal communication shows that there is no plan in this regard.
Thanks for the feedback.

**Comment by ByteZhang1024** [comment]
We shut it down without any more questions.

**Comment by shikiroot** [comment]
Both OKX and Bitget Wallet have DOH, should reconsider this issue?

**Comment by shikiroot** [comment]
> We shut it down without any more questions.

Both OKX and Bitget Wallet have DOH, should reconsider this issue?

**Comment by shikiroot** [comment]
> > We shut it down without any more questions.
> 
> Both OKX and Bitget Wallet have DOH, should reconsider this issue?

DNS security is also an important part of web3 security. I think.
