### ISSUE TITLE
[BUG]:you guys I need personal assistance I used my backup on Google drive and it's given me chain nan id

### ISSUE THREAD

**Issue by vehicles4real** [OneKeyHQ/app-monorepo#3896]
**Prerequisites**
Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked to make sure that this issue has not already been filed
- [x] I've asked for help in the [OneKey Discord](https://discord.com/invite/onekey) before filing this issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ByteZhang1024** [comment]
So what is your specific question? Please explain it in detail.

**Comment by vehicles4real** [comment]
i need my chain id
