### ISSUE TITLE
[Feature] 什么时候客户端能支持wallet connect v2

### ISSUE THREAD

**Issue by AxyLm** [OneKeyHQ/app-monorepo#3912]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Community & Quick support**

- [Community Forum](https://github.com/orgs/OneKeyHQ/discussions). Best for: help with building, discussion about best practices.
- [Discord](https://discord.gg/onekey). Best for: sharing your ideas and hanging out with the community.

**Additional context**
![image](https://github.com/OneKeyHQ/app-monorepo/assets/48370746/2ca2f8da-c948-4052-a1d9-52faa9a2b01a)
![image](https://github.com/OneKeyHQ/app-monorepo/assets/48370746/3a4c710e-85ee-423e-a26f-4b469dcd5fdb)

**Comment by ByteZhang1024** [comment]
We have support for v4.8.0.

**Comment by AxyLm** [comment]
![image](https://github.com/OneKeyHQ/app-monorepo/assets/48370746/899f02e2-488c-4bda-9eb2-82772d58e67b)

**Comment by AxyLm** [comment]
mac os m1 pro
4.17.0-2023112931

**Comment by ByteZhang1024** [comment]
How do you use it. Not a mobile client, desktop?

**Comment by AxyLm** [comment]
![image](https://github.com/OneKeyHQ/app-monorepo/assets/48370746/571e6eb2-527f-49a7-8222-35a5ede8f4cc)
@ByteZhang1024

**Comment by ByteZhang1024** [comment]
I checked to make sure. It is not supported yet, we are still working on x version, and will add v2 support later.

**Comment by AxyLm** [comment]
ok, thank you!
