### ISSUE TITLE
[BUG]: Pressing TAB before input password on the login-screen

### ISSUE THREAD

**Issue by jk-85** [OneKeyHQ/app-monorepo#3915]
- [X ] I checked to make sure that this issue has not already been filed

**Describe the bug**
I don't know which windows version I have from the wallet, but I can press TAB multiple times and don't have to input my password to unluck the wallet. I can switch through multiple info-messages pressing TAB.

**Expected behavior**
Nothing should happen unless the wallet is unlocked.

**Screenshots**
![grafik](https://github.com/OneKeyHQ/app-monorepo/assets/13134932/ed4c7281-0c63-4eac-803d-cbe8e5a4df93)

**Desktop (please complete the following information):**
 - OS: Windows 7

**Comment by jk-85** [comment]
You can also copy your public address even you didn't type in your password.

**Comment by ByteZhang1024** [comment]
Thanks for the feedback.
