### ISSUE TITLE
Disable Telematry Data (This project glows in the dark 👮✨)

### ISSUE THREAD

**Issue by animencoding** [OneKeyHQ/app-monorepo#3927]
# Prerequisites
Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ x] I checked to make sure that this issue has not already been filed
- [ ] I've asked for help in the [OneKey Discord](https://discord.com/invite/onekey) before filing this issue. (i don't have a discord acconut) 

## Summary
Telematry collection, what kind of info you guys collect? anyway to disable telematry 

From your Privacy Policy it says
We collect your Personal Information, including but not limited to your mobile device information, operation records, transaction records and wallet addresses.
## Expected Behavior
An option to disable every single Telematry 

## Current Behaviour
Insecure by default 

## Possible Solution
New option to remove all kinds Telematry

## Context

Peace of mind

yes very useful 

## Environment

* Operating System:
* App Version:

**Comment by ByteZhang1024** [comment]
It hasn't been collected yet. 
It is being planned, mainly to collect some necessary information for safety and compliance.

**Comment by animencoding** [comment]
lol -> "**safety** and compliance"

Oh you guys don't glow in the dark yet 
maybe until you have "enough" users than make sudden change to catch them all

i hope you put some notice before you starting doing so
