### ISSUE TITLE
[BUG]:ios安卓真机打包暗黑模式创建钱包页面为浅色模式 web与模拟器运行正常

### ISSUE THREAD

**Issue by weixiaojian001** [OneKeyHQ/app-monorepo#3954]
ios安卓真机打包暗黑模式创建钱包页面为浅色模式 web与模拟器运行正常
<img width="274" alt="image" src="https://github.com/OneKeyHQ/app-monorepo/assets/38640468/9f275ea4-6183-45c5-a960-0d812021a65f">

**Comment by ByteZhang1024** [comment]
感谢报告，后续版本会优化。
