### ISSUE TITLE
[BUG]: nostr event accountsChanged not working

### ISSUE THREAD

**Issue by helllosolana** [OneKeyHQ/app-monorepo#3998]
```
window.nostr.on('accountsChanged', (accounts) => {  
    // Handle the new accounts, or lack thereof.
    // "accounts" will always be an array, but it can be empty.
});
window.nostr.off('accountsChanged');
```

this is not working

**Comment by originalix** [comment]
The [Nip07](https://github.com/nostr-protocol/nips/blob/master/07.md) protocol does not include an 'on' event listener method. Has this feature been supported in any current protocol yet?

**Comment by helllosolana** [comment]
yes, alby wallet and okx wallet already support

**Comment by originalix** [comment]
Thank you for the feedback. We will support these two new methods and expect to have them fixed in the next version release.

**Comment by originalix** [comment]
We have fixed the issue, and it will be resolved in the next release. @TouchFan
