### ISSUE TITLE
[BUG]:  Errors when building IOS, the application does not work from TestFlight or ad-hoc

### ISSUE THREAD

**Issue by ArtemFlutterDev** [OneKeyHQ/app-monorepo#4037]
The application compiles with errors but works if launched via yarn ios, but if uploaded via Xcode in TestFlight the application does not open
I used a build from the onekey branch 3-4 days ago

node: 20.0.0
yarn: 3.5.0
OS: MacOs Sonoma 14.2.1
Xcode:15.1
![image](https://github.com/OneKeyHQ/app-monorepo/assets/74657601/b61ea3c0-3253-4059-9353-2c8a3f0e1e3e)
![image](https://github.com/OneKeyHQ/app-monorepo/assets/74657601/4429c0d0-a63a-405b-b2da-8e9994453d51)

**Comment by ByteZhang1024** [comment]
Need to manually downgrade to Xcode 14 We don't support Xcode 15 yet.

**Comment by ByteZhang1024** [comment]
If there are no more questions, we'll close.
