### ISSUE TITLE
open older wallet files?

### ISSUE THREAD

**Issue by dchmelik** [OneKeyHQ/app-monorepo#4049]
**Describe the solution you'd like**
Enable to open older wallet files?  For example, ethereum (ETH) original desktop wallets such as Mist always had wallet files which were standard/openable through later ones such as MyCrypto (desktop development is dead a few years) so those should become openable in OneKey.  It's much simpler/quicker for users to open wallet files than (too involved/slow) have to find & copy & write/paste in a private key or seed words.  I see OneKey can use many cryptocurrencies besides ETH, so am not limiting suggestion to it, though is main interest in this case.

**Comment by ByteZhang1024** [comment]
Are you talking about the ETH keystore file? Maybe not planned for now.

**Comment by dchmelik** [comment]
yes
