### ISSUE TITLE
Add support for QTUM blockchain

### ISSUE THREAD

**Issue by k1tzu** [OneKeyHQ/app-monorepo#4095]
I'm having trouble understanding the architecture of blockchain modules within your wallet. And really need to add QTUM blockchain support.

Maybe it's tricky if not possible to add that blockchain to the wallet, you know better.

Or maybe you have docs on how to create such adapter? I could write it by myself then. Or better pay someone to write it for me.

**Comment by ByteZhang1024** [comment]
https://github.com/OneKeyHQ/app-monorepo/pull/3919
You can refer to it first.
