### ISSUE TITLE
[BUG]:Unable to resolve "@onekeyhq/app/src/hardware/OnekeyLite" from "../kit/src/views/Hardware/OnekeyLite/Backup/index.tsx"

### ISSUE THREAD

**Issue by ithfay** [OneKeyHQ/app-monorepo#4101]
This error occurred when I debugged to the real Android device. But this file exists locally. How to solve this problem

<img width="733" alt="image" src="https://github.com/OneKeyHQ/app-monorepo/assets/139560438/5c7c335a-1e92-4853-a9ed-5ab3d2b14582">
<img width="360" alt="image" src="https://github.com/OneKeyHQ/app-monorepo/assets/139560438/43b62d38-f173-40ed-a9ef-b43548b092ab">

**Comment by ByteZhang1024** [comment]
Never encountered this problem before.
You can try clean and try again.
