### ISSUE TITLE
[BUG]: Transactions with USDC/Sol are not executed (pending forever)

### ISSUE THREAD

**Issue by kirillt** [OneKeyHQ/app-monorepo#4108]
Transactions hang in pending state forever. They don't reach the network.

**To Reproduce**
Normal use-case with USDC Solana:
1. Open wallet, switch to Solana network.
2. Start new transfer: input recipient address and transfer amount.
3. Submit the transaction.
4. The transaction appears in the history.

Actual result:
1. The transaction is marked as "pending", this won't change.
2. Explorer doesn't see the transaction: https://explorer.solana.com/tx/5xPh33qZabTH1xpTSCZf5yaZnpoRKRinzYxevpsehSvqfaUaNfRu3dnwbJEi934t9gx4a2qwycT69xUD8GfWrWZu

**Expected behavior**
Transaction must be visible in the explorer even if it's not confirmed yet. Label "pending" should disappear eventually.

**Screenshots**
![lenovo-xwd-2024-02-01_10-55-26](https://github.com/OneKeyHQ/app-monorepo/assets/581023/cb2d57a9-223b-42f5-9743-2163e88affe4)

**Log**
[log.txt](https://github.com/OneKeyHQ/app-monorepo/files/14122080/log.txt)

**Desktop (please complete the following information):**
 - OS: Fedora Linux
 - Browser: AppImage
 - Version: 4.19.0

**Comment by ByteZhang1024** [comment]
It's a transaction that was initiated in Onekey, right?
We will not delete your transaction history, this is a decentralized network and prevents Full nodes from unexpected results, such as transactions being packaged by other nodes.

We may consider optimizing it later, but it won't go away for a long time, and we may consider deleting it or displaying a failure if we can't find it for more than 24 or 48 hours.

**Comment by kirillt** [comment]
@ByteZhang1024 yes, the tx was initiated in OneKey.

The issue isn't that it is marked as pending. The real issues is that the tx isn't really sent out. I remember having succeeded sending Solana and USDC/Solana before. But that day all transactions in OneKey were just hanging forever. It wasn't caused by state of the network — Solflare sent same amount to same recipient immediately.

**Comment by ByteZhang1024** [comment]
I think it's caused by the rpc node, we only record the history after the broadcast deal is successful. Looks like there was a rpc node problem that dropped the transaction.

**Comment by kirillt** [comment]
@ByteZhang1024 probably yes. Is only one RPC node used or there is a pool, or maybe possible to configure nodes manually as a workaround when specific RPC nodes are down?

**Comment by ByteZhang1024** [comment]
At present, it may only be an exception of the node, which will be optimized in the future.
