### ISSUE TITLE
[BUG]: can't connect to tokenproof.xyz

### ISSUE THREAD

**Issue by ivanbaldo** [OneKeyHQ/app-monorepo#4124]
**Describe the bug**
Can't connect from Firefox Web nor from Android to tokenproof.xyz.
The sign-in message doesn't show on OneKey.

**To Reproduce**
1. Go to 'tokenproof.xyz' or open the mobile app.
2. Click on 'Connect Wallet'
3. Search for 'OneKey'

**Expected behavior**
OneKey shows the sign in confirmation message and TokenProof accepts the connection.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 20.04
 - Browser Firefox 122 on the https://app.onekey.so/ website
 - Version of OneKey 4.20.0-2024020225

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A2
 - OS: Android 10
 - Browser native apps used
 - Version 4.20.0-2024020225

**Comment by ivanbaldo** [comment]
This is the so.onekey.app.wallet-latest.log, the error seems to be:
`[ERROR]  walletConnect | walletConnectV2.responseCallRequest ERROR | Error: Calling [personal_sign] ERROR:  Mismatched networks. Please switch OneKey Wallet current network to chainId=8453`
[so.onekey.app.wallet-latest.log](https://github.com/OneKeyHQ/app-monorepo/files/14284910/so.onekey.app.wallet-latest.log)

**Comment by ivanbaldo** [comment]
Maybe this is related https://github.com/MetaMask/metamask-mobile/issues/8380

**Comment by ivanbaldo** [comment]
Are we using the dependencies and versions equal or later than the specified in https://github.com/WalletConnect/walletconnect-monorepo/issues/4089#issuecomment-1929834527 ?

**Comment by QuincySx** [comment]
You can try again. It's worked out.

**Comment by ByteZhang1024** [comment]
You can try again. It's worked out.

**Comment by ByteZhang1024** [comment]
It's already fixed. Turn it on if there's a problem.
