### ISSUE TITLE
The experience of onekey in android

### ISSUE THREAD

**Issue by TrustDec** [OneKeyHQ/app-monorepo#4177]
Onekey has a very bad experience in android. It is also developed by react-native. Why is Rainbow smooth on Android, but OneKey is stuck?

**Comment by ByteZhang1024** [comment]
We're working on improving the experience and it will be out soon.

**Comment by TrustDec** [comment]
Looking forward to the new version.

**Comment by ByteZhang1024** [comment]
You can now try out the new version.
