### ISSUE TITLE
钱包在这次升级后conflux espace网络出现抓取GAS费失败的情况，望技术团队尽快处理

### ISSUE THREAD

**Issue by JSCT789** [OneKeyHQ/app-monorepo#4322]
# Prerequisites
Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I checked to make sure that this issue has not already been filed
- [ ] I've asked for help in the [OneKey Discord](https://discord.com/invite/onekey) before filing this issue.

## Environment

* Operating System:
* App Version:

**Comment by ByteZhang1024** [comment]
没有发现这个问题，可以检查一下自己的网络。
