### ISSUE TITLE
[BUG]: 拉去代码运行报错ios

### ISSUE THREAD

**Issue by mnz12138** [OneKeyHQ/app-monorepo#4339]
Called object type 'facebook::flipper::SocketCertificateProvider' (aka 'int') is not a function or function pointer
<img width="1189" alt="image" src="https://github.com/OneKeyHQ/app-monorepo/assets/13588391/5990b2ab-0812-4575-87c3-b0a59a87245a">

**Comment by ByteZhang1024** [comment]
https://github.com/OneKeyHQ/app-monorepo/pull/4342
关注一下这里。

**Comment by mnz12138** [comment]
搞定的话，滴我一下

**Comment by mnz12138** [comment]
> #4342 关注一下这里。

我目前在onekey分支，大概什么时候可以搞定运行

**Comment by ByteZhang1024** [comment]
Onekey 分支不会有这个问题的，建议修改运行环境。
https://github.com/OneKeyHQ/app-monorepo/issues/4037

**Comment by mnz12138** [comment]
> Onekey 分支不会有这个问题的，建议修改运行环境。 #4037

好的,我试试xcode14

**Comment by mnz12138** [comment]
> Onekey 分支不会有这个问题的，建议修改运行环境。 #4037

有考虑过适配Xcode15么

**Comment by ByteZhang1024** [comment]
没有适配计划。

**Comment by mnz12138** [comment]
> 没有适配计划。

<img width="532" alt="image" src="https://github.com/OneKeyHQ/app-monorepo/assets/13588391/78fea670-57a5-4c46-b3a4-d145b39bb958">

**Comment by ByteZhang1024** [comment]
是的，Onekey 分支没有适配计划。

**Comment by mnz12138** [comment]
> 是的，Onekey 分支没有适配计划。

是放弃onekey分支了么，4月底就不能打包上传苹果了

**Comment by ByteZhang1024** [comment]
是的

**Comment by mnz12138** [comment]
> 是的

那以后你们OneKey App更新是在哪个分支上升级维护呢

**Comment by ByteZhang1024** [comment]
x

**Comment by ByteZhang1024** [comment]
I'll close this issue if there are no further questions.
