### ISSUE TITLE
Support Electroneum (ETN) Network

### ISSUE THREAD

**Issue by bonifacio123** [OneKeyHQ/app-monorepo#4357]
Network Name: Electroneum SmartChain
RPC URL: http://rpc.electroneum.com
Chain ID: 52014
Currency Symbol: ETN

This is not an Ethereum coin, rather, it has EVM compatibility where one can use an Ethereum address and Metamask or equivalent to manage account.

Thank you

https://developer.electroneum.com/migration-to-smart-chain/how-to-migrate/cli-wallet-users

**Comment by ByteZhang1024** [comment]
You can add it yourself using https://chainlist.org/?search=electroneum
