### ISSUE TITLE
[Feature] Add Sepolia Faucet or Holesky Faucet to test staking

### ISSUE THREAD

**Issue by markaltmaier** [OneKeyHQ/app-monorepo#4490]
Currently the Goerli faucet is deprecated and no longer running, in which we can't test the staking feature.
Please add Sepolia Faucet or Holesky Faucet

**Comment by revan-zhang** [comment]
Hi @Mustafa-Agha, in the latest version, we support both Sepolia and Garnet Holesky testnets. Thanks for your reminder.
