### ISSUE TITLE
[Feature] Support CKB chain for Watch-only Accounts

### ISSUE THREAD

**Issue by chaoticlonghair** [OneKeyHQ/app-monorepo#4512]
**Is your feature request related to a problem? Please describe.**

CKB chain is not supported for Watch-only Accounts.

**Describe the solution you'd like**

Support CKB chain for Watch-only Accounts.

**Describe alternatives you've considered**

None.

**Community & Quick support**

- [Community Forum](https://github.com/orgs/OneKeyHQ/discussions). Best for: help with building, discussion about best practices.
- [Discord](https://discord.gg/onekey). Best for: sharing your ideas and hanging out with the community.

**Additional context**

None.

**Comment by ByteZhang1024** [comment]
There is no plan at the moment.
