### ISSUE TITLE
[BUG]: Xcode 15 build is required

### ISSUE THREAD

**Issue by markaltmaier** [OneKeyHQ/app-monorepo#4533]
SDK version issue - This app was built with the iOS 16.4 SDK. Starting April 29, 2024, all iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution.

**Comment by Mohammed990990** [comment]
https://github.com/OneKeyHQ/app-monorepo/commit/53307367e248c0a833ed7e39ab7388c3eaf61d85

**Comment by ByteZhang1024** [comment]
It's already supported, you can look at CI.

**Comment by markaltmaier** [comment]
Yeah, it was updated in the last release 4.24.0 version
