### ISSUE TITLE
[BUG]: Batch addition cannot exceed 100

### ISSUE THREAD

**Issue by AxyLm** [OneKeyHQ/app-monorepo#4538]
**Prerequisites**
Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I checked to make sure that this issue has not already been filed
- [ ] I've asked for help in the [OneKey Discord](https://discord.com/invite/onekey) before filing this issue.

**Describe the bug**

**Expected behavior**
1-100
101-200
201-300

**Screenshots**
<img width="433" alt="image" src="https://github.com/OneKeyHQ/app-monorepo/assets/48370746/ee38b419-926a-463b-b261-79e798c2a1e8">

**Desktop (please complete the following information):**
 - any

**Smartphone (please complete the following information):**
 - any

**Comment by ByteZhang1024** [comment]
这个不是从 index 到 index。是从 index 开始生成多少个。你填写的是 200 个。我们单次对多只能生成 100 个。

**Comment by AxyLm** [comment]
ok!
