### ISSUE TITLE
[BUG]: Clarify License

### ISSUE THREAD

**Issue by ghost** [OneKeyHQ/app-monorepo#4587]
The license specified here: https://github.com/OneKeyHQ/app-monorepo/blob/onekey/LICENSE.md

is conflicting with the one here: https://github.com/OneKeyHQ/app-monorepo/blob/8cb5177ccea4a1c2bbae87564102440060c18c9b/README.md?plain=1#L176

**Comment by revan-zhang** [comment]
Sorry for the late reply, our [app-monorepo](https://github.com/OneKeyHQ/app-monorepo) agreement is here https://github.com/OneKeyHQ/app-monorepo/blob/x/LICENSE.md, you can take a look on it. Thanks!
