### ISSUE TITLE
[Feature] Firefox Support

### ISSUE THREAD

**Issue by zelosleone** [OneKeyHQ/app-monorepo#4601]
Using the open source and nonprofit browser Firefox, please make an addon for it.

**Comment by rayston92** [comment]
Hi @zelosleone 

Thanks for your suggestion, but we won't be supporting the Firefox browser anymore. In the past, we've often had issues with Firefox rejections, and given its market share, maintaining support for it would increase our development workload. Please consider using Chrome or other Chromium-based browsers instead.
