### ISSUE TITLE
[Feature] Allow to add more monero accounts

### ISSUE THREAD

**Issue by ghost** [OneKeyHQ/app-monorepo#4682]
**Is your feature request related to a problem? Please describe.**
I'd like to add multiple monero accounts like it is possible for other currencies like bitcoin.

**Describe the solution you'd like**
Possibility to add more xmr accounts if one already exists.

**Describe alternatives you've considered**
Managing the other accounts outside of onekey

**Community & Quick support**

- [Community Forum](https://github.com/orgs/OneKeyHQ/discussions). Best for: help with building, discussion about best practices.
- [Discord](https://discord.gg/onekey). Best for: sharing your ideas and hanging out with the community.

**Additional context**

**Comment by revan-zhang** [comment]
The new version of onekey no longer supports xmr tokens and needs to be operated on the official client.
