### ISSUE TITLE
dependency ‘BitGo/blake2b’ install error

### ISSUE THREAD

**Issue by Chiuvenz** [OneKeyHQ/app-monorepo#498]
an error occurred when I install dependencies

![image](https://user-images.githubusercontent.com/103477285/162888821-532d4b09-6514-4b0d-bf1e-337473f3e06b.png)

It seems to be related to this Issue: https://github.com/trezor/trezor-utxo-lib/issues/14

**Comment by revan-zhang** [comment]
Please try `./clean_workspace.sh` at project root folder. It will remove all node_modules and clean yarn cache.

If this way not work, it is likely to be caused by network-related reasons.

**Comment by Chiuvenz** [comment]
> Please try `./clean_workspace.sh` at project root folder. It will remove all node_modules and clean yarn cache.
> 
> If this way not work, it is likely to be caused by network-related reasons.

Thanks a lot! It's the weak network for me indeed.

**Comment by Chiuvenz** [comment]
> Please try `./clean_workspace.sh` at project root folder. It will remove all node_modules and clean yarn cache.
> 
> If this way not work, it is likely to be caused by network-related reasons.

Thanks a lot! It's the weak network for me indeed.

**Comment by KaidonWong** [comment]
> > Please try `./clean_workspace.sh` at project root folder. It will remove all node_modules and clean yarn cache.
> > If this way not work, it is likely to be caused by network-related reasons.
> 
> Thanks a lot! It's the weak network for me indeed.

Is it pure network issue? have you change the link https://github.com/BitGo/blake2b   to  
 https://github.com/BitGo/BitGoJS/tree/master/modules/blake2b

**Comment by KaidonWong** [comment]
> > Please try `./clean_workspace.sh` at project root folder. It will remove all node_modules and clean yarn cache.
> > If this way not work, it is likely to be caused by network-related reasons.
> 
> Thanks a lot! It's the weak network for me indeed.

I have the same problem. could you tell me what exactly did you do to solve this?

**Comment by revan-zhang** [comment]
@KaidonWong 

The module **@trezor/utxo-lib** depend on this commit, [https://github.com/BitGo/blake2b/commit/6268e6dd678661e0acc4359e9171b97eb1ebf8ac](https://github.com/BitGo/blake2b/commit/6268e6dd678661e0acc4359e9171b97eb1ebf8ac)

It's download from github.com not yarn registry, so for this problem the most possible is  the yarn command cannot access github.com in your shell.

**Comment by revan-zhang** [comment]
As you can see in our yarn.lock
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/18140164/163582495-0d845e02-cca4-4786-b3bf-187eab816004.png">

**Comment by KaidonWong** [comment]
@loaddss Thank you for your guide. But I can access github.com in command console. How could yarn not able to access github. Is there anything I can do to fix this?

**Comment by revan-zhang** [comment]
@KaidonWong 

Have you tried `./clean_workspace.sh` script at root? It clean your yarn local cache and remove all node_modules at workspaces. After this job try `yarn --verbose` again. Try to find out what's the real reason for this issue.

**Comment by KaidonWong** [comment]
I did try './clean_workspace.sh', and it is not working.
![image](https://user-images.githubusercontent.com/41094868/163591817-506eb7f5-af77-461c-82d9-4b80a2ebc2c6.png)
the picture above is the result when I run 'git ls-remote --heads --tags https://github.com/BitGo/blake2b'. And below is the error message when I run yarn. As you can see, there is indeed no '"6268e..." commit in the repository.
![image](https://user-images.githubusercontent.com/41094868/163592148-60755ec8-91ea-4df0-a986-dcbdb4cbd23d.png)

**Comment by KaidonWong** [comment]
> I did try './clean_workspace.sh', and it is not working. ![image](https://user-images.githubusercontent.com/41094868/163591817-506eb7f5-af77-461c-82d9-4b80a2ebc2c6.png) the picture above is the result when I run 'git ls-remote --heads --tags https://github.com/BitGo/blake2b'. And below is the error message when I run yarn. As you can see, there is indeed no '"6268e..." commit in the repository. ![image](https://user-images.githubusercontent.com/41094868/163592148-60755ec8-91ea-4df0-a986-dcbdb4cbd23d.png)

@loaddss

**Comment by KaidonWong** [comment]
@loaddss  I have edited the yarn.lock file to change the blake2d url to another existing commits(555a4,,.), and this time the above issue didn't show up. However, I run into this error, could you tell me how to solve this?
![image](https://user-images.githubusercontent.com/41094868/163655644-da5aa26c-ad5b-4d1e-abdf-475dbc5ed4d3.png)

**Comment by KaidonWong** [comment]
@loaddss   I have edited the yarn.lock file to change the blake2d url to another existing commits(555a4,,.), and this time the above issue didn't show up. However, I run into this error, could you tell me how to solve this?
![image](https://user-images.githubusercontent.com/41094868/163656585-c400214c-473d-4b3c-8cde-17e8bdffd5c3.png)

**Comment by KaidonWong** [comment]
My platform is Windows not MacOS, is it the possible cause?

**Comment by KaidonWong** [comment]
Problem solved by itself the next day, it is indeed a network issue.
