### ISSUE TITLE
[BUG]: Can not access api with error 403

### ISSUE THREAD

**Issue by LuoHuacheng** [OneKeyHQ/app-monorepo#4991]
**Prerequisites**
Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I checked to make sure that this issue has not already been filed
- [x] I've asked for help in the [OneKey Discord](https://discord.com/invite/onekey) before filing this issue.

**Describe the bug**
When I tried to run the code the http error 403 came to me, after some debugging I found this problem happened because of the `host` parameter but I don't konw how to fix it

**To Reproduce**
1. clone the code
2. install dependencies
3. run yarn run app:web:proxy

**Expected behavior**
the api can return data properly

**Screenshots**
![image](https://github.com/OneKeyHQ/app-monorepo/assets/14214871/5e3d70b5-9111-4184-bfb8-a9a485566120)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 126.0.0.0

**Comment by revan-zhang** [comment]
The http status code 403 means we have restrictions on user access in specific areas.

**Comment by LuoHuacheng** [comment]
> The http status code 403 means we have restrictions on user access in specific areas.

So will this problem solve if I change my network proxies to the areas not in the restrict list ?
And can you please tell me which areas are not in the restrict list now ?
