### ISSUE TITLE
[BUG]:Unrecognized VM option 'MaxPermSize=512m' Error: Could not create the Java Virtual Machine. 

### ISSUE THREAD

**Issue by dhruvin771** [OneKeyHQ/app-monorepo#5048]
Java Version: 21
Node Version: 16

I am facing an error while trying to run the APK in Android. 

![image](https://github.com/OneKeyHQ/app-monorepo/assets/91345575/718c4bf4-d73a-44bf-86a9-8f417028b528)
![image](https://github.com/OneKeyHQ/app-monorepo/assets/91345575/6640c68f-a2a9-4d31-8081-d3b10dedc0fa)
![image](https://github.com/OneKeyHQ/app-monorepo/assets/91345575/e1e61783-4b59-4ad6-896a-9ddfe928901d)

**Comment by revan-zhang** [comment]
Hi @dhruvin771 , we have released the new version at x branch. Please try again to check if the issue is ok now.
