### ISSUE TITLE
[BUG]: Can't make a Polkadot transaction 

### ISSUE THREAD

**Issue by hassnian** [OneKeyHQ/app-monorepo#5066]
**Describe the bug**
I'm trying to transfer some funds from my polkadot wallet and I'm unable to do so , I'm getting an error when trying to make a transaction.

**To Reproduce**
1. Go to 1key.so
2. Connect wallet
3. Select Polkadot
4. Select Account 2 (in my case)
5. Try making a polkadot transaction
6. Add address
7. Click send all balance
8. See error

**Expected behavior**
Should allow me to make a transaction

**Screenshots**

![image](https://github.com/OneKeyHQ/app-monorepo/assets/44554284/2b1c2a13-96df-4c8d-8455-7a5c51d2caa2)

**Desktop (please complete the following information):**
 - OS: Mac os
 - Browser Brave
 - Version [Version 1.58.131 Chromium: 117.0.5938.92 (Official Build) (arm64)](https://brave.com/latest/)

**Comment by ByteZhang1024** [comment]
Polkadot has been updated when running online, we need to update it and it is under preparation.

**Comment by hassnian** [comment]
@ByteZhang1024 any updates?; I still can't transfer my funds on any of the interfaces

**Comment by ByteZhang1024** [comment]
Under test.
