### ISSUE TITLE
desktop pakcage Build fails on macOS 12.3 due to missing /usr/bin/python

### ISSUE THREAD

**Issue by gaodeng** [OneKeyHQ/app-monorepo#510]
Possible solution: Upgrade electron-builder

**Comment by revan-zhang** [comment]
Duplicated with https://github.com/OneKeyHQ/app-monorepo/pull/508 , has fixed this morning, thanks!

**Comment by revan-zhang** [comment]
Our current desktop version has support for arm64 platform already. I have tried [v1.0.1 for M1 OSX system](https://github.com/OneKeyHQ/app-monorepo/releases), works fine!

**Comment by gaodeng** [comment]
Yes, the x64 build can be run via rosetta. But the arm64 version runs a bit faster on apple chips.

**Comment by revan-zhang** [comment]
Good point! Thanks for your reply.

Could you please resolve the conflict in PR and resubmit the config about the system support part for arm64, we also do some technical investigation.

**Comment by gaodeng** [comment]
Okay, no problem.
