### ISSUE TITLE
[Feature] Any plan to support TON (The Open Network)?

### ISSUE THREAD

**Issue by shikiroot** [OneKeyHQ/app-monorepo#5112]
https://ton.org

**Comment by ByteZhang1024** [comment]
It's already in the plan, and currently we are fully focused on ensuring the release of the V5 App.

**Comment by revan-zhang** [comment]
Released at [v5.2.0](https://github.com/OneKeyHQ/app-monorepo/releases/tag/v5.2.0).Thanks.
