### ISSUE TITLE
[BUG]: tron网络调用 wallet_switchEthereumChain 切换网络提示 'method not found'

### ISSUE THREAD

**Issue by liubin595338764** [OneKeyHQ/app-monorepo#5241]
**Prerequisites**
Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

**Describe the bug**
tron网络调用 wallet_switchEthereumChain 切换网络提示 'method not found'

**To Reproduce**
我当前是tron mainnet：0x2b6653dc， 想要切换到tron shasta: 0x94a9059e 

或者我当前是EVM网络，需要切换到Tron网， 都会报错：

code：
```
window.$onekey.tron.request({
    method:'wallet_switchEthereumChain',
    params:[{ chainId: '0x94a9059e' }]
})
```

**Expected behavior**
可以正确切换到chainId网

**Screenshots**

<img width="408" alt="image" src="https://github.com/user-attachments/assets/df4f08da-efd6-4479-8f6a-5d194e246a72">

**Desktop (please complete the following information):**
 - OS: mac 14.5
 - Browser chrome
 - Version Chrome/126.0.0.0

**Comment by ByteZhang1024** [comment]
你的使用方式，和相应的方法，是根据什么 api 调用的，可以给个参考吗。

**Comment by liubin595338764** [comment]
> 你的使用方式，和相应的方法，是根据什么 api 调用的，可以给个参考吗。

是根据tronLink调用的，这个方法在tronLink里面是生效的

**Comment by ByteZhang1024** [comment]
有相关文档吗。

**Comment by liubin595338764** [comment]
> 有相关文档吗。

https://github.com/tronprotocol/tips/issues/464
这个是他们的开发人员在issues里面记录的，

**Comment by ByteZhang1024** [comment]
看到了对应的 TIP 1193 我们没支持，看起来也没什么 dApp 兼容。我们评估一下这个需求。

**Comment by liubin595338764** [comment]
@ByteZhang1024 请问你们有其他的方法可以切换tron网络吗

**Comment by ByteZhang1024** [comment]
没有我们只支持主网。

**Comment by liubin595338764** [comment]
> 没有我们只支持主网。

但是如果我在EVM网络，也没有办法可以切换到Tron的主网。在Tron主网的时候却可以切换到EVM网络

**Comment by ByteZhang1024** [comment]
通过什么方式切的，给个例子。
我们这种跨链间的 api 还没有定义。

**Comment by ByteZhang1024** [comment]
我们 V5 你其实不用切，想用什么网络连什么网络就好。支持一个网站同时连接多个链。

**Comment by ByteZhang1024** [comment]
暂时不考虑兼容这套 api。

**Comment by liubin595338764** [comment]
@ByteZhang1024 onekey浏览器扩展升级到V5之后，都不能链接tron的，我看了几个网站，都不行：
https://sun.io/?lang=en-US
https://app.justlend.org/homeNew?lang=en-US
https://dapp-example.onekeytest.com/tron   

麻烦指导一下，是彻底不支持，还是正在修复这个问题，会马上修复支持吗？

**Comment by ByteZhang1024** [comment]
试了一下最新的 Chrome 插件，没有复现你说的问题。
怀疑是你开了其他插件冲突导致的。

**Comment by liubin595338764** [comment]
https://sun.io/?lang=en-US
@ByteZhang1024 比如sun这个网站，点击OneKey & TronLink连接钱包时无效，我就只安装了onekey浏览器扩展，其他的扩展禁用了。我是直接在桌面浏览器里面访问sun.io，不是onekey里面的浏览器访问

https://github.com/user-attachments/assets/0b59c43b-1d7e-440a-9964-2080cd220a5c

**Comment by ByteZhang1024** [comment]
Chrome 插件端、OneKey Mac 桌面端。均没有出现你说的问题。
有没有尝试重启过。一般情况连接反应不会这么快，能像这样连点。

如果还有问题，可以再导出个日志提交一下看看。
https://help.onekey.so/hc/requests/new

**Comment by liubin595338764** [comment]
@ByteZhang1024 
你看这个视频可能比较清楚
这里还有日志文件：
[OneKeyLogs-20240829T064119483Z.txt](https://github.com/user-attachments/files/16794028/OneKeyLogs-20240829T064119483Z.txt)



https://github.com/user-attachments/assets/aa2ec660-5077-4ed9-b3c3-dba9fd01cf4c

**Comment by ByteZhang1024** [comment]
复现到了是 BUG。正在排查原因。

**Comment by liubin595338764** [comment]
@ByteZhang1024  谢谢，靠谱！
