### ISSUE TITLE
[BUG]: The eth balance is not correct, so app wont let me sign the transaction even though I have eth

### ISSUE THREAD

**Issue by jorg1piano** [OneKeyHQ/app-monorepo#5251]
When swapping on side chains like BASE the eth balance is not updated when swapping from another token into eth. It is also not reflected when sending eth to the base chain wallet. 

I know the funds are there because I can see them on chain, but if I refresh the token list in the wallet the incorrect state is still shown.

The same incorrect balance is shown both on the mobile app and on the mac os app.

It is probably related to #3521. (I also have this problem with some microcap tokens)

The worst part is that I can't even swap via uniswap because the app does not let me sign the transaction since it does not think I have eth available. Please stop trying to be clever and just let us sign the transaction and let it fail. I'm certain I'm on the correct chain and that I have the balances I think I have. 

Steps to reproduce
1. Open the app
2. Do some swaps on uniswap (some real shitcoins prehaps)
3. Inspect the balances shown in the app vs on chain.

**Comment by ByteZhang1024** [comment]
I would like to know how long this error state will last, or if it is permanent.

**Comment by ByteZhang1024** [comment]
If convenient, please send your address to our customer service in a private message so we can check it.
https://help.onekey.so/hc/requests/new or https://discord.com/channels/868309113942196295/912695369656316014

**Comment by jorg1piano** [comment]
I just opened the app and the right eth amount was there. So it seems to be a cashing issue from your servers.

Please don't close this ticket. The root issue is not resolved. I still have balances that just infinitely loads as described in #3521

**Comment by jorg1piano** [comment]
I submitted the address and statelogs to :
https://help.onekey.so/hc/requests/new

**Comment by ByteZhang1024** [comment]
The previous version 4.x had this issue as it was using a public RPC server. 
To improve the experience in this area, we have switched to our own server in version 5. By the way, have you started using version 5.x yet?

**Comment by jorg1piano** [comment]
I'm on the latest version available to me on the app store. My iOS version is 17.3? Do I need a newer ios version to get 5.x?

**Comment by ByteZhang1024** [comment]
iOS、Android will need to patiently wait for another two weeks, while the Desktop version is already in public beta across all platforms. You can check it out on our official website.

**Comment by jorg1piano** [comment]
The issues seem to have been resolved on the 5.x version (mac OS). Will report back when the 5.x iOS app is also out in beta.

**Comment by jorg1piano** [comment]
When will 5.x be available on iPhone? The mobile app is completely unusable atm...

**Comment by jorg1piano** [comment]
Still not possible to see the correct balances in the app on mobile 4.24.0

**Comment by ByteZhang1024** [comment]
It's 5.x been reviewed in stores.
