### ISSUE TITLE
[Need help] yarn ios fail on Apple M1 macOS

### ISSUE THREAD

**Issue by Naeemo** [OneKeyHQ/app-monorepo#533]
It's probably M1/arm related base on the error message, tried Google around but no progress.
Thanks.

---
full output of `yarn ios`:
```        
yarn run v1.22.17
$ expo run:ios
› Planning build
› Executing react-native-config Pods/react-native-config » [CP-User] Config codegen
› Executing expo-constants Pods/EXConstants » [CP-User] Generate app.config for prebuilt Constants.manifest
› Compiling react-native-config Pods/react-native-config » ReactNativeConfig.m
› Packaging react-native-config Pods/react-native-config » libreact-native-config.a
› Executing OneKeyWallet » Start Packager on http://localhost:8081
› Linking   OneKeyWallet » OneKeyWallet

❌  ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/naeemo/Workspace/github/app-monorepo/packages/app/ios/OneKeyWallet/Frameworks/GPChannelSDKCore.framework/GPChannelSDKCore' for architecture arm64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)



› 2 error(s), and 0 warning(s)

Failed to build iOS project. "xcodebuild" exited with error code 65.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by revan-zhang** [comment]
Currently for our IOS project, can only run at intel OSX Simulator. Because our dependiency GPChannelSDKCore for security data communication between APP and OneKey Lite doesn't support arm64 platform.

Our developer using M1 is debug at real device not simulator.

In the furture we will add a flag to ignore GPChannelSDKCore compile. Currently for M1 user can only run desktop, browser extension, web and android simulator environment.

**Comment by Naeemo** [comment]
> Currently for our IOS project, can only run at intel OSX Simulator. Because our dependiency GPChannelSDKCore for security data communication between APP and OneKey Lite doesn't support arm64 platform.
> 
> 
> 
> Our developer using M1 is debug at real device not simulator.
> 
> 
> 
> In the furture we will add a flag to ignore GPChannelSDKCore compile. Currently for M1 user can only run desktop, browser extension, web and android simulator environment.

OK, 👌

**Comment by jacko06v** [comment]
i didn't see that, i got a lot of error but finally i ran the app on ios simulator on arm64
-1 download repo
-2 go on packages/app and edit react-native version inside package.json to 0.64.3
-3 go on main directory and run yarn
-4 go inside packages/app/ios 
-5 run `sudo gem install cocoapods`
-6 cd .. 
-7 run `export NODE_OPTIONS=--max-old-space-size=8192`
-8 run react-native run-ios
-9 run expo start --dev-client  

this worked for me

**Comment by revan-zhang** [comment]
@jacko06v @Naeemo 
After this PR https://github.com/OneKeyHQ/app-monorepo/pull/552, our project is working at OSX M1 arm64 simulator now.
