### ISSUE TITLE
[BUG]: Search field don't get focus when opening dropdown to search for chain

### ISSUE THREAD

**Issue by jorg1piano** [OneKeyHQ/app-monorepo#5395]
When clicking the dropdown to select a chain, the search field should get focus. The intent of the user when clicking this is to search, so it should have focus. 

**Steps to reproduce the behavior:**
1. Open the app on desktop( I'm using mac) 
2. Press on the dropdown to select a chain

**Expected behavior**
The search field should get focus.

**Screenshots**
<img width="108" alt="image" src="https://github.com/user-attachments/assets/d04443e9-700f-4ec2-814e-27183d396da4">

**Desktop:**
 - OS: Mac OS
 - Browser chrome
 - Version 5.x

**Comment by franco-chan** [comment]
Hi @jorg1piano, thanks for the feedback. This is good advice that would improve productivity when switching a network. We plan to auto-focus on the search field on non-native platforms, including Desktops and extensions.

**Comment by franco-chan** [comment]
https://github.com/OneKeyHQ/app-monorepo/pull/5880
