### ISSUE TITLE
[BUG]: changing network leaves the balance of old account in the new one

### ISSUE THREAD

**Issue by markaltmaier** [OneKeyHQ/app-monorepo#5655]
On version 5.1.2 on android device

When I change the network for dogecoin which I have a balance in my account#1 and #2

Now, if changed to etherium, which I have zero balance, however, the account#1 and account#2 in the accounts menu don't update to zero it leaves the old balance number. I don't know if this is by design or if it's a bug, but it's definitely confusing.

![VideoCapture_20240827-162603.jpg](https://github.com/user-attachments/assets/12308ce3-0afc-4419-ab8d-b8501b230087)

**Comment by ByteZhang1024** [comment]
The display here is separate from the network type. It shows the aggregated amount for the current account across all networks.
