### ISSUE TITLE
Question: how the browser detect the wallet for injection to the dapps

### ISSUE THREAD

**Issue by anatoly7778** [OneKeyHQ/app-monorepo#5681]
Can you please share how the dapp detects the wallet app as the photos I shared. 

can you share documents and the site provider and any information that will be help 

![IMG_6852](https://github.com/user-attachments/assets/d563a2b4-8f44-4e6b-a7b2-b308970b2837)

thanks

**Comment by ByteZhang1024** [comment]
I'm not very clear about these details either, and I'm not sure what specifically you want to know.

**Comment by anatoly7778** [comment]
What sdk api providers you use for browser , walletconnect , metamask rainbow ?

**Comment by ByteZhang1024** [comment]
https://eips.ethereum.org/EIPS/eip-1193
https://eips.ethereum.org/EIPS/eip-6963
