### ISSUE TITLE
Running Android Throws libreactnativemmkv.so Error 

### ISSUE THREAD

**Issue by kr-jayendra** [OneKeyHQ/app-monorepo#5703]
## Issue: Error Running Android App :
- libreactnativemmkv.so Not Found, AppRegistry.registerComponent Not Called

## Environment:

- Node.js: 20.17.0 (LTS)
- Yarn: 4.1.0
- JDK: 17
- gradle : 8.3.0
-  react-native-mmkv - 2.10.2

## Steps to Reproduce:
- Cloned the repository and installed the necessary dependencies, ensuring compatibility with the specified versions of Node.js, Yarn, Git LFS, and JDK.
- Attempted to run the Android app using the command: yarn app:android.

## Observed Behavior:
The app fails to launch on Android, throwing the following error:
```
Error: Exception in HostFunction: java.lang.UnsatisfiedLinkError: dlopen failed: library "libreactnativemmkv.so" not found, js engine: hermes
```
Additionally, another error is observed:
```
ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```
## Potential Causes:
- The libreactnativemmkv.so file might not be properly linked or bundled, leading to the UnsatisfiedLinkError.
- The AppRegistry.registerComponent error suggests that there might be an issue with the Metro bundler setup or the way components are registered in the project, especially with Hermes as the JS engine.

## Request for Assistance:
- Could there be an issue with the way react-native-mmkv is being linked or configured, especially with Hermes?
- Are there additional steps required for Hermes when using react-native-mmkv?
- Any guidance on resolving the component registration issue with Metro would be appreciated.

## Additional Notes:
- The project uses a recent version of React Native with Hermes as the JS engine.
- Are there any known compatibility issues with Node.js 20.17.0 or Yarn 4.1.0 that might affect the build process?

**Comment by kr-jayendra** [comment]
any updates on this please

**Comment by ByteZhang1024** [comment]
We haven't encountered this kind of problem before, so we may not be able to help you.

**Comment by kr-jayendra** [comment]
Can you please let us know the working environment details?  @ByteZhang1024

**Comment by ByteZhang1024** [comment]
You can see all the details in the [Eas.json](https://github.com/OneKeyHQ/app-monorepo/blob/x/apps/mobile/eas.json).

**Comment by kr-jayendra** [comment]
Hi, I encountered an issue to resolve it by updating the gradle.properties file.
```
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
```
This change was made in the apps/mobile/android/gradle.properties file, and it resolved the issue for me. It might be worth updating this line in the repository to support multiple architectures.

**Comment by ByteZhang1024** [comment]
I understand. It seems this issue was caused by your specific running platform. We won't consider modifying it for now.
