### ISSUE TITLE
Question: api endpoint

### ISSUE THREAD

**Issue by anatoly7778** [OneKeyHQ/app-monorepo#5779]
Hi, 

I see your backend endpoint not open source, 

Can you please share with us what api providers you use on your backend .

wallet activity 
swap function 
market 
risk detection 

And if you have another endpoint using on the private backend share it with us please. 

Thank you.

**Comment by ByteZhang1024** [comment]
Sorry, we cannot disclose all the details at this time. If you need to use OneKey API services, please contact our business team.

**Comment by anatoly7778** [comment]
Your nodes is private too ?
