### ISSUE TITLE
Bitcoin 的 derivation path 和标准的 BIP 不同

### ISSUE THREAD

**Issue by XWJACK** [OneKeyHQ/app-monorepo#5948]
https://github.com/OneKeyHQ/app-monorepo/blob/03a9ed837a121dbe9979248aa13d8c8e6f6e7163/packages/kit-bg/src/vaults/impls/btc/settings.ts#L32-L82

[`m / purpose' / coin_type' / account' / change / address_index`](https://github.com/bitcoin/bips/blob/master/bip-0086.mediawiki)

导致生成的地址无法兼容其他钱包，而且也没有自定义`derivation path`地方

**Comment by originalix** [comment]
请问希望派生的具体路径是什么？

**Comment by XWJACK** [comment]
其他钱包: `m/86'/${COINTYPE_BTC}'/0'/0/${INDEX_PLACEHOLDER}`

unisat wallet: 
<img width="371" alt="image" src="https://github.com/user-attachments/assets/56b9704c-5236-4026-99fd-db1d17d45509">
sparrow wallet: 
<img width="639" alt="image" src="https://github.com/user-attachments/assets/052ff32f-5c21-4b73-8b4e-4766e593d1a1">

**Comment by originalix** [comment]
每个 Account，应该account_index 位递增索引，而不是像 unisat 一样在最后一位 address_index 递增。否则 Bitcoin 的账户的找零地址和 Receive 地址就无法使用新地址

**Comment by originalix** [comment]
![image](https://github.com/user-attachments/assets/4c09e2fe-c67f-4b56-9707-32f42dee133d)

请看这张 Sparrow 文档的截图，Sparrow， electrum 这类老牌 bitcoin 钱包的派生也是在 account_index 位递增。

OneKey 在 Bitcoin 账户的派生是标准的

https://sparrowwallet.com/docs/quick-start.html

**Comment by XWJACK** [comment]
是的，这也仅仅出现在新帐户创建的情况，而更多使用的是找零地址（okx、unisat...）。

所以是否考虑增加自定义选项，这样从其他平台导入的钱包就不会出现找不到地址问题。

或者针对btc新增找零地址的选项（这样可能对非专业级用户造成困扰）

**Comment by originalix** [comment]
已经有计划会在接下来的迭代里做找零地址， 并且会提供是否开启找零地址的开关（避免新手用户对地址变更的困惑）
