### ISSUE TITLE
yarn ios error

### ISSUE THREAD

**Issue by jacko06v** [OneKeyHQ/app-monorepo#654]
when i run `yarn ios` i get 
`error: unable to attach DB: error: accessing build database "/Users/jacopomosconi/Library/Developer/Xcode/DerivedData/OneKeyWallet-clovgltvlcltewaayddbggaboclu/Build/Intermediates.noindex/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.`

**Comment by linleiqin** [comment]
Try to clean the Derived Data, hope this helps you:
[https://programmingwithswift.com/delete-derived-data-xcode/](https://programmingwithswift.com/delete-derived-data-xcode/)

**Comment by jacko06v** [comment]
> Try to clean the Derived Data, hope this helps you: https://programmingwithswift.com/delete-derived-data-xcode/

thank you! that fixed my problem, after that i had iphoneos_deployment_target so i changed the deployment target inside every pods from 8 to 10, when i run yarn ios now i get the error below:

```2022-05-01 14:27:57.134 xcodebuild[47362:4260929] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-05-01 14:27:57.135 xcodebuild[47362:4260929] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
** BUILD FAILED **


The following build commands failed:
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'ExpoModulesCore' from project 'Pods')
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'lottie-react-native' from project 'Pods')
        PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/jacopomosconi/Library/Developer/Xcode/DerivedData/OneKeyWallet-clovgltvlcltewaayddbggaboclu/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-337605CB7CDF90939BEBF863ED22C375.sh (in target 'FBReactNativeSpec' from project 'Pods')
(3 failures)```
