### ISSUE TITLE
Problem while using command Yarn

### ISSUE THREAD

**Issue by akzhol0921** [OneKeyHQ/app-monorepo#664]
![image](https://user-images.githubusercontent.com/43620746/166975796-6b4f177b-64bf-4482-b9f7-b6d7b12dee6d.png)
![image](https://user-images.githubusercontent.com/43620746/166975820-b3d715c5-7738-4572-80d5-bef06ddee807.png)
after download this project i tried use yarn to install packages and this happen

**Comment by revan-zhang** [comment]
Currently our script for postinstall at package.json `"postinstall": "yarn setup:env && husky install && yarn build:connect && yarn copy:inject && patch-package",` doesn't support windows system.

For windows user, could you please run these command one by one and modify the command to suit the windows system.

**Comment by rayston92** [comment]
@akzhol0921 did you fix this problem?

**Comment by akzhol0921** [comment]
Problem is solved by using docker dev environment.
